---
title: "ACS and Google Trends (2010-2019) Cross-Sectional Data"
author: "Yu-Hsuan Liu"
date: "March 2nd, 2021"
output:
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
  word_document: default
header-includes:
- \usepackage{pdflscape}
- \usepackage{caption}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
---




```{r, results='hide', message=FALSE, warning = FALSE, echo = F}
library(dplyr)
library(xtable)
library(prettyR)
library(ggplot2)
library(tidyr)
library(glue)
library(gtable)
library(grid)
library(gridExtra)
library(stargazer)
library(haven)
library(reshape2)
library(MatchIt)
library(maps)
library(plm)
library(multiwayvcov)
library(lmtest)
library(readxl)
library(janitor)
library(hablar)
library(psych)
library(psycho)
library(tidyverse)
library(geojsonio)
library(geojsonsf)
library(sp)
library(RColorBrewer)
library(rnaturalearth)
library(rnaturalearthdata)
library(sf)
library(broom)
library(mapproj)
library(ggpubr)
library(viridis)
library(pastecs)
library(kableExtra)
library(knitr)
library(MASS)
library(semPlot)
library(corrplot)


eval = TRUE
options(scipen = 999)
options(xtable.comment = FALSE)
options(knitr.kable.NA = '')
knitr::opts_chunk$set(cache = TRUE)
theme_set(theme_bw())
```




```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
## We dont use 2005-2009 data because there is no internet and vehicle data!

# read ACS 2005-2009
acs_05_09 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2005_2009.csv")

# read ACS 2006-2010
acs_06_10 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2006_2010.csv")

# read ACS 2007-2011
acs_07_11 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2007_2011.csv")

# read ACS 2008-2012
acs_08_12 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2008_2012.csv")

# read ACS 2009-2013
acs_09_13 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2009_2013.csv")

# read ACS 2010-2014
acs_10_14 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2010_2014.csv")

# read ACS 2011-2015
acs_11_15 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2011_2015.csv")

# read ACS 2012-2016
acs_12_16 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2012_2016.csv")

# read ACS 2013-2017
acs_13_17 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2013_2017.csv")

# read ACS 2014-2018
acs_14_18 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2014_2018.csv")

# read ACS 2015-2019
acs_15_19 <- read.csv("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/ACS_2015_2019.csv")
```


\newpage
\blandscape
```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
# read needed ACS variables lists and IDs
acs_variables_id <- read_excel("C:/Users/tosea/Google-Trend/datasets/ACS(5 year estimates)/Variable Lists and IDs.xlsx")
print(xtable(acs_variables_id), scalebox = 0.8)
```
\elandscape
\newpage

```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}

#Read walkcross file (county to dmas)
walkcross <- read.csv("county_dma_crosswalk_harvard.csv")

#process cross-sectional data 2010-2019
pre_process_ACS <- function(data, walkcross, variable_id, year){
  #To make ID as column names
  data <- data %>%
    row_to_names(row_number = 1)
  
  #Keep needed variables
  data <- data[,c(variable_id["ACS ID"])[[1]]]
  data <- data %>% 
    rename(
      FIPS = Geo_FIPS,
      )
  #Make string to numberic
  data <- data %>% retype()
  
  #Aggregate county level data into DMAs
  
    ## Merge ACS with walkcross
  data_new <- merge(data, walkcross,by="FIPS")
  
    ## Drop columns not needed
  data_new = subset(data_new, select = -c(FIPS, STATE, COUNTY,  Harvard_DMA))
  
    ## Group_by DMAs
  data_DMA <- data_new %>% 
    group_by(DMA) %>% 
    summarise_each(funs(sum))

  return(data_DMA)
  }

pre_acs_15_19 <- pre_process_ACS(acs_15_19, walkcross, acs_variables_id, "2019")
pre_acs_10_14 <- pre_process_ACS(acs_10_14, walkcross, acs_variables_id, "2014")
pre_acs_15_19
#add numeric variables
acs_10_19 <- (pre_acs_15_19[2:25] + pre_acs_10_14[2:25])/2

#add DMA and ID
acs_10_19["DMA"] <- pre_acs_15_19$DMA
acs_10_19["DMAINDEX"] <- pre_acs_15_19$DMAINDEX

```



```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#Write a function to process acs_10_19 (combining and calculating "rates")
post_process_ACS <- function(data_DMA, year){
  data_DMA["Percentage of Foreign Born"] <- data_DMA$SE_A06001_003/data_DMA$SE_A00001_001*100
  
    ## Percentage of MoveIn: (Moved)/Total Pop. Use function scale to standardize data 
    ## as the data of mean == 0, sd == 1
  data_DMA["Percentage of MoveIn"] <- 
    (data_DMA$SE_A08001_003 +
       data_DMA$SE_A08001_004 +
       data_DMA$SE_A08001_005 +
       data_DMA$SE_A08001_006 )/
       data_DMA$SE_A00001_001*100
   ## Alpha Test of Percentage of MoveIn
  print(alpha(data.frame("Move Within Same County" = data_DMA$SE_A08001_003,
                   "Move from different county within same state" = data_DMA$SE_A08001_004,
                   "Move from different state" = data_DMA$SE_A08001_005,
                   "Move from abroad" = data_DMA$SE_A08001_006)))
  
   ## Percentage of Renter
  data_DMA["Percentage of Renter"] <- data_DMA$SE_A10062B_001/data_DMA$SE_A00001_001*100
  
  
  ## Mobility Index
  ## Move In + Renter
  data_DMA["Mobility Index"] <- 
    #standardized percentage of renter
    scale(data_DMA$SE_A10062B_001/data_DMA$SE_A00001_001) +
    #standardized percentage of movein
    scale((data_DMA$SE_A08001_003 +
       data_DMA$SE_A08001_004 +
       data_DMA$SE_A08001_005 +
       data_DMA$SE_A08001_006 )/
       data_DMA$SE_A00001_001)
  
  ## Alpha Test
  print(alpha(data.frame("Percentage of MoveIn" = scale(data_DMA["Percentage of MoveIn"]),
                   "Percentage of Renter" = scale(data_DMA["Percentage of Renter"]))))
  
   ## Concentrated Disadvantage Index 
   ##(Unemployed + Female-headed Households + Poverty Families + Less than High School)
   ## (Using "scale" func to standardize)
  data_DMA["Concentrated Disadvantaged Index"] <- 
    scale(data_DMA$SE_A17002_006/data_DMA$SE_A00001_001) +
    scale(data_DMA$SE_A10009_007/data_DMA$SE_A10008_001) +
    scale(data_DMA$SE_A13002_002/data_DMA$SE_A10008_001) +
    scale(data_DMA$SE_A12001_002/data_DMA$SE_A00001_001)
  
  data_DMA["Percentage of Unemployed"] <- 
  data_DMA$SE_A17002_006/data_DMA$SE_A00001_001*100
  
  data_DMA["Percentage of Female Headed Households"] <- 
  data_DMA$SE_A10009_007/data_DMA$SE_A10008_001*100
    
  data_DMA["Percentage of Poverty"] <- 
  data_DMA$SE_A13002_002/data_DMA$SE_A10008_001*100
  
   ## Alpha Test of Concentrated Disadvantage Index 
  print(alpha(data.frame("Unemployed" = scale(data_DMA$SE_A17002_006/data_DMA$SE_A00001_001),
                   "Female Headed Households" = scale(data_DMA$SE_A10009_007/data_DMA$SE_A10008_001),
                   "Families Income Below Poverty" = scale(data_DMA$SE_A13002_00/data_DMA$SE_A10008_001),
                   "Less than High School" = scale(data_DMA$SE_A12001_002/data_DMA$SE_A00001_001))))
  
   ## Heterogeneity Index (The Probability that two persons are in different race)
   ## = 1 - (The probability that two persons are in the same race)
  data_DMA["Heterogeneity Index"] <-
    1 - (
      #percentage of Non-Hispanic White ^2
      (data_DMA$SE_A04001_003/data_DMA$SE_A00001_001)^2 + 
        #percentage of Hispanic or Latino ^2
        (data_DMA$SE_A04001_010/data_DMA$SE_A00001_001)^2 +
        #percentage of Non-Hispanic Native and Indian ^2
        (data_DMA$SE_A04001_005/data_DMA$SE_A00001_001)^2 +
        #percentage of Non-Hispanic Asian ^2
        (data_DMA$SE_A04001_006/data_DMA$SE_A00001_001)^2 +
        #percentage of Non-Hispanic Pacific Islander ^2
        (data_DMA$SE_A04001_007/data_DMA$SE_A00001_001)^2 +
        #percentage of Non-Hispanic Black ^2
        (data_DMA$SE_A04001_004/data_DMA$SE_A00001_001)^2
    )
  
  #Percentage of Young Males
    data_DMA["Percentage of Young Males"] <- 
    (data_DMA$SE_A02002_007 +
       data_DMA$SE_A02002_006
     )/data_DMA$SE_A00001_001*100
  
  #Percentage of Dropp Out
  data_DMA["Percentage of Dropped Out"] <- data_DMA$SE_A12003_002/data_DMA$SE_A12003_001*100
  
  #Percentage of Divorced
  data_DMA["Percentage of Divorced"] <- data_DMA$SE_A11001_006/data_DMA$SE_A00001_001*100
  
  #log population
  data_DMA["Popualtion(logged)"] <- log(data_DMA$SE_A00001_001)
  
  #insert year value
  data_DMA$year = year
  
  #Percentage of Less Than High School (Population 25 Years and Over: Less than High School)
  data_DMA["Less than High School"] <- data_DMA$SE_A12001_002/data_DMA$SE_A00001_001*100
  
  #Percentage of Non-Hispanic White
  data_DMA["Percentage of White"] <- data_DMA$SE_A04001_003/data_DMA$SE_A00001_001*100
  
  #Percentage of Non-Hispanic Black
  data_DMA["Percentage of Black"] <- data_DMA$SE_A04001_004/data_DMA$SE_A00001_001*100
  
  #Percentage of Hispanic
  data_DMA["Percentage of Hispanic"] <- data_DMA$SE_A04001_010/data_DMA$SE_A00001_001*100
  
  #Percentage of Non-Hispanic Native and Indian
  data_DMA["Percentage of Native Americans"] <- data_DMA$SE_A04001_005/data_DMA$SE_A00001_001*100
  
  return(data_DMA[c("DMA",
                    "DMAINDEX",
                    "year",
                    "Percentage of Foreign Born",
                    "Percentage of MoveIn",
                    "Percentage of Renter",
                    "Mobility Index",
                    "Concentrated Disadvantaged Index",
                    "Percentage of Unemployed",
                    "Percentage of Female Headed Households",
                    "Percentage of Poverty",
                    "Heterogeneity Index",
                    "Percentage of Young Males",
                    "Percentage of Dropped Out",
                    "Percentage of Divorced",
                    "Popualtion(logged)",
                    "Less than High School",
                    "Percentage of White",
                    "Percentage of Black",
                    "Percentage of Hispanic",
                    "Percentage of Native Americans",
                    "SE_A00001_001")])
}
acs_10_19_dma <- post_process_ACS(acs_10_19, "2010-2019")


```

```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
# Processing UCR Crime 
ucr <- read.csv("C://Users//tosea//Google-Trend//datasets//UCR_Crime_ICPSR//ucr_offenses_known_yearly_1960_2019_csv//offenses_known_yearly_1960_2019.csv")

#write a function to process UCR data
ucr_func <- function(ucr, year1, year2){
  #filter needed year range
  ucr_year <- ucr[(ucr$year >= year1) & (ucr$year <= year2), ]
  #keep needed variables
  ucr_year <- ucr_year[c("fips_state_county_code", 
                                 "population", 
                                 "actual_rape_total",
                                 "actual_burg_total",
                                 "actual_theft_total",
                                 "actual_mtr_veh_theft_total",
                         "actual_murder",
                         "actual_manslaughter",
                         "actual_assault_total",
                         "actual_robbery_total")]
  ucr_year$homicide <- ucr_year$actual_murder + ucr_year$actual_manslaughter
  #aggregate single years to a period needed
  ucr_year_fips <- ucr_year %>% 
      group_by(fips_state_county_code) %>% 
      summarise_each(funs(sum))
  
  #rename FIPS
  ucr_year_fips <- ucr_year_fips%>% 
      rename(
        FIPS = fips_state_county_code,
        )
  
  #merge with walkcross, prepare to group_by DMAs
  ucr_year_fips <- merge(ucr_year_fips, walkcross,by="FIPS")
  
  #Drop unneeded variables
  ucr_year_fips <- subset(ucr_year_fips,
                              select = -c(FIPS, STATE, COUNTY, DMAINDEX, Harvard_DMA))
  
  ## Group_by DMAs
  ucr_year_DMA <- ucr_year_fips %>% 
      group_by(DMA) %>% 
      summarise_each(funs(sum))
  
  #crime rate
  ucr_year_DMA_rate <- ucr_year_DMA[-1]/ucr_year_DMA$population
  
  
  #add DMA back to the data
  ucr_year_DMA_rate["DMA"] <- ucr_year_DMA$DMA
  
  #rename
  colnames(ucr_year_DMA_rate) <- c("POP", "UCR Rape", "UCR Burglary",
                                   "UCR Larceny", "UCR MVT", 
                                   "UCR Murder", "UCR Manslaughter", 
                                   "UCR Homicide", "UCR Assault", "UCR Robbery","DMA")
  ucr_year_DMA_rate <- ucr_year_DMA_rate[c("POP", "UCR Rape", "UCR Burglary",
                                   "UCR Larceny", "UCR MVT", 
                                   "UCR Homicide", "UCR Assault", "UCR Robbery", "DMA")]
  return(ucr_year_DMA_rate)
}

ucr_2010_2019 <- ucr_func(ucr, 2010, 2019)[,-c(1)]

```



```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#Read Google Trends data


gt_10_19 <- read.csv("10-19_gt_crime/GT_Crime_SingleKeywordsOrigin.csv")


gt_10_19 <- gt_10_19[c("DMA",
           "MVT_10_19",
           "Burglary_10_19",
           "Larceny_10_19",
           "Rape_10_19")
           ] 
```


```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#control variables (Internet Usage and Median Vehicles per Families)
cv = read.csv("sima.csv")

#FIPS to DMAs
cv <- merge(cv, walkcross,by="FIPS")

#drop unneeded columns
cv <- subset(cv, select = -c(FIPS, STATE, COUNTY, DMAINDEX, Harvard_DMA))

# group by DMAs (in Stata it is collapese(sum))
cv_dma <- cv %>% 
    group_by(DMA) %>% 
    summarise_each(funs(sum))

# for median Vehicle, we need to use average (in Stata it is collapese(mean))
cv_dma_mean <- cv %>% 
    group_by(DMA) %>% 
    summarise_each(funs(mean))


############################################
#use cv year 2010-2019 for data 2010-2019
cv_dma["Internet Usage HH 10_19"] <- 
  ((cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2011 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2012 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2013 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2014 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2015 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2016 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2017 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2018 +
     cv_dma$X..Households.Using...Internet..Any.Internet.Online.usage..2019
   )/9)/
  ((cv_dma$X..Households..HHs...2011 + 
      cv_dma$X..Households..HHs...2012 +
      cv_dma$X..Households..HHs...2013 +
      cv_dma$X..Households..HHs...2014 +
      cv_dma$X..Households..HHs...2015 + 
      cv_dma$X..Households..HHs...2016 +
      cv_dma$X..Households..HHs...2017 +
      cv_dma$X..Households..HHs...2018 +
      cv_dma$X..Households..HHs...2019)/9)*100


cv_dma["Median Vehicle HH 10_19"] <- 
  (cv_dma_mean$Household..Median.Vehicles..2011 + 
     cv_dma_mean$Household..Median.Vehicles..2012 + 
     cv_dma_mean$Household..Median.Vehicles..2013 + 
     cv_dma_mean$Household..Median.Vehicles..2014 +
     cv_dma_mean$Household..Median.Vehicles..2015 + 
     cv_dma_mean$Household..Median.Vehicles..2016 + 
     cv_dma_mean$Household..Median.Vehicles..2017 + 
     cv_dma_mean$Household..Median.Vehicles..2018 +
     cv_dma_mean$Household..Median.Vehicles..2019
   )/9


cv_dma_10_19 <- cv_dma[c("DMA", 
                   "Internet Usage HH 10_19",
                   "Median Vehicle HH 10_19")]

```

```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
# Add Drug Mobility 2010-2018 into the Cross Sectional Data

drug_sup <- read.csv("datasets/substance_abuse_data_12_16/NCHS_Drug_Poisoning_Mortality_by_County__United_States.csv")

#filter years which are larger than and equal to 2010
drug_sup <- drug_sup %>%
  subset(drug_sup$Year >= 2010)

#average counts of all years
drug_sup_fips <- drug_sup[c(1,5)] %>%
  group_by(FIPS) %>%
  summarize_each(mean)

#rename 
colnames(drug_sup_fips) <- c("FIPS", "Drug_Mortality_Count_10_18")

#from county to DMA
drug_sup_dma <- drug_sup_fips %>% 
  merge(walkcross, by = "FIPS")

drug_sup_dma_10_18 <- drug_sup_dma[c("DMA", "Drug_Mortality_Count_10_18")] %>%
  group_by(DMA) %>%
  summarize_each(sum)
drug_temp <- merge(acs_10_19_dma, drug_sup_dma_10_18, by = "DMA")

#calculate the mortality rate
drug_temp$Drug.Mortality.Rate <- 
  drug_temp$Drug_Mortality_Count_10_18/drug_temp$SE_A00001_001*1000000

drug_mortality_rate_10_18 <- drug_temp[c("DMA", "Drug.Mortality.Rate")]

```


```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#law enforcement employments
law_enforce_10_14 <- retype(read.csv("datasets/police_2010_2019/law enforcement employments 10-14.csv")[c(2, 4)])
law_enforce_15_19 <- retype(read.csv("datasets/police_2010_2019/law enforcement employments 15-19.csv")[c(2, 4)])

colnames(law_enforce_10_14) <- c("FIPS", "law_enforcement_employments_10_14")
colnames(law_enforce_15_19) <- c("FIPS", "law_enforcement_employments_15_19")

law_enforce_10_19 <- merge(law_enforce_10_14, law_enforce_15_19, by = "FIPS")

law_enforce_10_19["law_enforcement_employments_10_19"] <- 
  (law_enforce_10_19["law_enforcement_employments_10_14"]+
  law_enforce_10_19["law_enforcement_employments_15_19"])/2
law_enforce_10_19_dma <- merge(
  law_enforce_10_19, walkcross, by = "FIPS")


law_enforce_10_19_dma <- law_enforce_10_19_dma %>%
  dplyr::select("DMA", "law_enforcement_employments_10_19") %>%
  group_by(DMA) %>%
  summarize_each(sum) %>%
  merge(acs_10_19_dma[c("DMA", "SE_A00001_001")], by = "DMA")

law_enforce_10_19_dma_per_thousand <- law_enforce_10_19_dma %>%
  mutate(law_enforcement_employments_10_19_per_thousand = 
           law_enforcement_employments_10_19/SE_A00001_001*1000) %>%
  dplyr::select("DMA", "law_enforcement_employments_10_19_per_thousand")

```


```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
total_10_19 <- 
  merge(
    merge(
      merge(
        merge(
          merge(
            gt_10_19, ucr_2010_2019, by = "DMA"), 
          acs_10_19,by = "DMA"), 
        drug_mortality_rate_10_18, by = "DMA"),
      law_enforce_10_19_dma_per_thousand, by = "DMA"),
    cv_dma_10_19, by = "DMA") %>%
  drop_na()



#process acs data after dropping na
acs_10_19 <- post_process_ACS(total_10_19, "2010-2019")
 
 
total_10_19 <- 
  merge(
    merge(
      merge(
        merge(
          merge(
            gt_10_19, ucr_2010_2019, by = "DMA"), 
          acs_10_19,by = "DMA"), 
        drug_mortality_rate_10_18, by = "DMA"),
      law_enforce_10_19_dma_per_thousand, by = "DMA"),
    cv_dma_10_19, by = "DMA")
total_10_19
rename_list <- c("DMA", 
                "GT.MVT", 
                "GT.Burglary", 
                "GT.Larceny", 
                "GT.Rape", 
                "UCR.Rape",
                "UCR.Burglary",
                "UCR.Larceny",
                "UCR.MVT",
                "UCR.Homicide",
                "UCR.Assault", 
                "UCR.Robbery", 
                "DMA.INDEX", 
                "year", 
                "Percentage.of.Foreign.Born",
                "Percentage.of.MoveIn",
                "Percentage.of.Renter",
                "Mobility.Index",
                "Concentrated.Disadvantage.Index",
                "Percentage.of.Unemployed",
                "Percentage.of.Female.Headed.Households",
                "Percentage.of.Poverty",
                "Heterogeneity.Index",
                "Percentage.of.Young.Males",
                "Percentage.of.Dropped.Out",
                "Percentage.of.Divorced",
                "Population.logged",
                "Less.than.High.School",
                "Percentage.of.White",
                "Percentage.of.Black",
                "Percentage.of.Hispanic",
                "Percentage.of.Indigenous",
                "Population",
                "Drug.Mortality.Rate",
                "Law.Enforce.per.Thousand",
                "Internet.Usage.HH",
                "Median.Vehicle.HH")

colnames(total_10_19) <- rename_list
```


```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}


# Covered DMAs and All DMAs charts AND Sort by Population
DMA_chart <-  data.frame(cbind(acs_10_19_dma$DMA, acs_10_19_dma$DMA  %in% total_10_19$DMA, as.numeric(acs_10_19_dma$SE_A00001_001)))
DMA_chart <- DMA_chart[order(DMA_chart$X2, as.numeric(DMA_chart$X3), decreasing = TRUE), ]
colnames(DMA_chart) <- c("Total DMA List", "107 DMA used in this study","Population") 

#Calculate the total coverage of the populaiton of the 107 DMAs
Percent_coverage <- sum(as.numeric(DMA_chart[DMA_chart$'107 DMA used in this study' == TRUE,]$Population))/sum(as.numeric(DMA_chart$Population))


DMA_chart$'Total DMA List' [DMA_chart$'Total DMA List'  == ''] <- 'Not Covered Area in DMAs'

write.csv(DMA_chart, file="DMA_population_table.csv", row.names=FALSE)
```




```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#get the 2010-2019 cross sectional data and drop na
final.data.2010_2019 <- total_10_19 %>%
  subset(select = -c(year)) %>%
  drop_na()
write.csv(final.data.2010_2019, file="final.data.2010_2019.csv", row.names=FALSE)

#rescale GT and UCR crime rates into 0-100 after dropping NA
dependent_variable_col_names <- c("GT.MVT", "GT.Burglary", "GT.Larceny", "GT.Rape",
                                  "UCR.MVT", "UCR.Burglary", "UCR.Larceny", 
                                  "UCR.Rape", "UCR.Homicide")

for (i in dependent_variable_col_names){
    final.data.2010_2019[[i]] <- final.data.2010_2019[[i]]/max(final.data.2010_2019[[i]])*100
  }
final.data.2010_2019[["UCR.Robbery"]] <- final.data.2010_2019[["UCR.Robbery"]]/max(final.data.2010_2019[["UCR.Robbery"]])*100
final.data.2010_2019[["UCR.Assault"]] <- final.data.2010_2019[["UCR.Assault"]]/max(final.data.2010_2019[["UCR.Assault"]])*100

operated_data_and_variables <- final.data.2010_2019[,c("UCR.MVT","UCR.Burglary","UCR.Homicide", "UCR.Robbery",
                                    "GT.MVT","GT.Burglary","GT.Larceny", "GT.Rape","UCR.Larceny", "UCR.Rape", 
                                    "Concentrated.Disadvantage.Index",
                                    #"Percentage.of.Unemployed",
                                    #"Percentage.of.Female.Headed.Households",
                                    #"Percentage.of.Poverty",
                                    #"Percentage.of.MoveIn",
                                    #"Percentage.of.Renter",
                                    "Mobility.Index",
                                    "Heterogeneity.Index",
                                    "Percentage.of.Foreign.Born", 
                                    #"Percentage.of.Black",
                                    #"Percentage.of.Hispanic", 
                                    #"Percentage.of.White",
                                    #"Percentage.of.Indigenous",
                                    "Percentage.of.Divorced",
                                    #"Less.than.High.School",
                                    "Percentage.of.Young.Males",
                                    "Drug.Mortality.Rate",
                                    #"Law.Enforce.per.Thousand",
                                    "Population.logged",
                                    "Internet.Usage.HH",
                                    "Median.Vehicle.HH")]
desc_10_19 <- round(t(stat.desc(operated_data_and_variables))[,c("mean", "std.dev", "min", "max")], 2)

desc_table <- cbind.data.frame(desc_10_19)
colnames(desc_table) <- c("Mean", "SD","Min", "Max") 
list_of_row_names <- c(   "UCR Motor Vehicle Theft", "UCR Burglary", "UCR Homicide", "UCR Robbery", 
                          "GT Motor Vehicle Theft", "GT Burglary", "GT Larceny", "GT Rape", "UCR Larceny", "UCR Rape",
                          "Concentrated Disadvantage Index", 
                          #"% Unemployed",
                          #"% Female Headed Households",
                          #"% Poverty",
                          #"% Move In", 
                          #"% Renter",
                          "Mobility Index",
                          "Heterogeneity Index",
                          "% Foreign Born", 
                          #"% Black", 
                          #"% Hispanic", 
                          #"% White", 
                          "% Divorced", 
                          #"% Less than High School", 
                          "% Young Males",
                          "Drug Mortality Rate",
                          #"Law Enforce per Thousand",
                          "Population(log)",
                          "% Internet Usage HH",
                          "Median Vehicle HH")

rownames(desc_table) <- list_of_row_names

```

\newpage
\blandscape
\captionsetup{width=20cm}
```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
final_desc_table <- kable(desc_table, longtable = T, booktabs = T, align = "c", format = "latex", linesep = "",
    caption = "Descriptive Statistics for 2010 to 2019", digits = 3) %>%

  kable_styling(position = "center", 
                latex_options = c("hold_position")) %>%
  pack_rows("Valid Crime Measures", 1, 4) %>%
  pack_rows("Crime Measures Needs to be Valid", 5, 10) %>%
  pack_rows("Common Covariates in Crime", 11, 17) %>%
  pack_rows("Control Variables", 18, 20) %>%
  column_spec(1, bold = F, width = "6cm") %>%
  column_spec(2, bold = F, width = "1cm") %>%
  column_spec(3, bold = F, width = "1cm") %>%
  column_spec(4, bold = F, width = "1cm") %>%
  column_spec(5, bold = F, width = "1cm") %>%
  footnote(number = c(paste("N = ", length(final.data.2010_2019$DMA), " DMAs."), "GT = Google Trends Crime Estimates.", "HH = Household"), footnote_as_chunk = T, threeparttable = T)
print(final_desc_table)

```
\elandscape
\newpage



```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
###Correlation Matrix Function
corstars <-function(x, method=c("pearson", "spearman"), removeTriangle=c("upper", "lower"),
                     result=c("none", "html", "latex")){
    #Compute correlation matrix
    require(Hmisc)
    x <- as.matrix(x)
    correlation_matrix<-rcorr(x, type=method[1])
    R <- correlation_matrix$r # Matrix of correlation coeficients
    p <- correlation_matrix$P # Matrix of p-value 
    
    ## Define notions for significance levels; spacing is important.
    mystars <- ifelse(p < .01, "**", ifelse(p < .05, "*\ ", "\ \ "))
    
    ## trunctuate the correlation matrix to two decimal
    R <- format(round(cbind(rep(-1.11, ncol(x)), R), 3))[,-1]
    ## build a new matrix that includes the correlations with their apropriate stars
    Rnew <- matrix(paste(R, mystars, sep=""), ncol=ncol(x))
    diag(Rnew) <- paste(diag(R), " ", sep="")
    rownames(Rnew) <- colnames(x)
    colnames(Rnew) <- paste(colnames(x), "", sep="")
    
    ## remove upper triangle of correlation matrix
    if(removeTriangle[1]=="upper"){
      Rnew <- as.matrix(Rnew)
      Rnew[upper.tri(Rnew, diag = TRUE)] <- ""
      Rnew <- as.data.frame(Rnew)
    }
    
    ## remove lower triangle of correlation matrix
    else if(removeTriangle[1]=="lower"){
      Rnew <- as.matrix(Rnew)
      Rnew[lower.tri(Rnew, diag = TRUE)] <- ""
      Rnew <- as.data.frame(Rnew)
    }
    
    ## remove last column and return the correlation matrix
    
    Rnew <- cbind(Rnew[1:length(Rnew)-1])
    if (result[1]=="none") return(Rnew)
    else{
      if(result[1]=="html") print(xtable(Rnew), type="html")
      else print(xtable(Rnew), type="latex") 
    }
} 
```




```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#Correlation Matrix
corr_variables <- final.data.2010_2019[,c("GT.MVT","GT.Burglary","GT.Larceny", "GT.Rape",
                                    "UCR.MVT","UCR.Burglary","UCR.Larceny", "UCR.Homicide",
                                    "UCR.Robbery","UCR.Rape")]
                                    #"Concentrated.Disadvantage.Index",
                                    #"Percentage.of.Unemployed",
                                    #"Percentage.of.Female.Headed.Households",
                                    #"Percentage.of.Poverty",
                                    #"Percentage.of.MoveIn",
                                    #"Percentage.of.Renter",
                                    #"Mobility.Index",
                                    #"Heterogeneity.Index",
                                    #"Percentage.of.Foreign.Born", 
                                    #"Percentage.of.Black",
                                    #"Percentage.of.Hispanic", 
                                    #"Percentage.of.White",
                                    #"Percentage.of.Divorced",
                                    #"Less.than.High.School",
                                    #"Percentage.of.Young.Males",
                                    #"Drug.Mortality.Rate",
                                    #"Law.Enforce.per.Thousand",
                                    #"Population.logged",
                                    #"Internet.Usage.HH",
                                    #"Median.Vehicle.HH"
                                    

cor_table <- corstars(corr_variables)

#insert index at the end of rowname
cor_table["new"] <- c("(1)", "(2)", "(3)", "(4)",
                        "(5)", "(6)", "(7)", "(8)",
                        "(9)", "(10)")
                      #"(11)", "(12)",
                      #  "(13)", "(14)", "(15)", "(16)",
                      #  "(17)", "(18)", "(19)") 
cor_table <- cor_table[,c(10, 1:9)]


#insert index as colnames
colnames(cor_table) <- c(" ", "(1)", "(2)", "(3)", "(4)",
                        "(5)", "(6)", "(7)", "(8)",
                        "(9)")
                        #"(10)", "(11)", "(12)",
                        #"(13)", "(14)", "(15)", "(16)",
                        #"(17)", "(18)")



rownames(cor_table) <- c("GT MVT", 
                         "GT Burglary", 
                         "GT Larceny", 
                         "GT Rape",
                         "UCR MVT", 
                         "UCR Burglary", 
                         "UCR Larceny", 
                         "UCR Homicide",
                         "UCR Robbery",
                         "UCR Rape")
                         #"CD Index", 
                          #"% Unemployed",
                          #"% Female Headed Households",
                          #"% Poverty",
                          #"% Move In", 
                          #"% Renter",
                          #"Mobility Index",
                          #"Heterogeneity Index",
                          #"% Foreign Born", 
                          #"% Black", 
                          #"% Hispanic", 
                          #"% White", 
                          #"% Divorced", 
                          #"% Less than High School", 
                          #"% Young Males",
                          #"Drug Mortality Rate",
                          #"Law Enforce per Thousand",
                          #"Population(log)",
                          #"% Internet Usage HH",
                          #"Median Vehicle HH")


```
\newpage
\blandscape
```{r}
mydata.cor = cor(corr_variables, method = c("spearman"))
colnames(mydata.cor) <- c("$MVT[GT]", "$Burglary[GT]", "$Larceny[GT]", "$Rape[GT]", "$MVT[UCR]", "$Burglary[UCR]", "$Larceny[UCR]", "$Homicide[UCR]", "$Robbery[UCR]", "$Rape[UCR]")
rownames(mydata.cor) <- c("$MVT[GT]", "$Burglary[GT]", "$Larceny[GT]", "$Rape[GT]", "$MVT[UCR]", "$Burglary[UCR]", "$Larceny[UCR]", "$Homicide[UCR]", "$Robbery[UCR]", "$Rape[UCR]")
corrplot(mydata.cor, tl.col = 'black')
```

\elandscape



\newpage
\blandscape
```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#col_width <- "0.8cm"
final_corr_table <- kable(cor_table, longtable = T, booktabs = T, 
                          align = "l",
                          format = "latex", linesep = "",
    caption = 'Correlation Matrix of All Measures') %>%
  kable_styling(#latex_options="scale_down", #font_size = 12,
                #position = "float_left", 
                bootstrap_options = "striped",
                full_width = F) %>%
  #column_spec(1, bold = F, width = "5cm") %>%
  #column_spec(2, bold = F, width = "1cm") %>%
  #column_spec(3, bold = F, width = col_width) %>%
  #column_spec(4, bold = F, width = col_width) %>%
  #column_spec(5, bold = F, width = col_width) %>%
  #column_spec(6, bold = F, width = col_width) %>%
  #column_spec(7, bold = F, width = col_width) %>%
  #column_spec(8, bold = F, width = col_width) %>%
  #column_spec(9, bold = F, width = col_width) %>%
  #column_spec(10, bold = F, width = col_width) %>%
  #column_spec(11, bold = F, width = col_width) %>%
  #column_spec(12, bold = F, width = col_width) %>%
  #column_spec(13, bold = F, width = col_width) %>%
  #column_spec(14, bold = F, width = col_width) %>%
  #column_spec(15, bold = F, width = col_width) %>%
  #column_spec(16, bold = F, width = col_width) %>%
  #column_spec(17, bold = F, width = col_width) %>%
  #column_spec(18, bold = F, width = col_width) %>%
  #column_spec(19, bold = F, width = col_width) %>%
  footnote(number = c("** = p < .01, * = p < .05;","GT = Google Tredns Crime Estimates", "MVT = Motor Vehicle Theft"),
                      #, "CD = Concentrated Disadvantage", "HH = Household")
                      number_title = "Note: ", 
           footnote_as_chunk = T, threeparttable = T)
print(final_corr_table) #,scalebox = 0.9)

```
\elandscape
\newpage


```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#write a OLS regression function (for one period 2010-2019)
lm_func <- function(data, y, control_Vehicle){
  data <- drop_na(data)
  if (control_Vehicle == FALSE){
    lm_model <- lm(data = data, 
                   data[[y]] ~ Concentrated.Disadvantage.Index +
                       #Percentage.of.Unemployed +
                       #Percentage.of.Female.Headed.Households +
                       #Percentage.of.Poverty +
                       #Percentage.of.MoveIn + 
                       #Percentage.of.Renter +
                       Mobility.Index +
                       Heterogeneity.Index +
                       Percentage.of.Foreign.Born + 
                       #Percentage.of.Black +
                       #Percentage.of.Hispanic + 
                       #Percentage.of.White +
                       Percentage.of.Divorced +
                       #Less.than.High.School +
                       Percentage.of.Young.Males +
                       Drug.Mortality.Rate +
                       #Law.Enforce.per.Thousand +
                       Population.logged +
                       Internet.Usage.HH)
  }
  else{
    lm_model <- lm(data = data, 
                   data[[y]] ~ Concentrated.Disadvantage.Index +
                     #Percentage.of.Unemployed +
                       #Percentage.of.Female.Headed.Households +
                       #Percentage.of.Poverty +
                       #Percentage.of.MoveIn + 
                       #Percentage.of.Renter +
                       Mobility.Index +
                       Heterogeneity.Index +
                       Percentage.of.Foreign.Born +
                       #Percentage.of.Black +
                       #Percentage.of.Hispanic + 
                       #Percentage.of.White +
                       Percentage.of.Divorced +
                       #Less.than.High.School +
                       Percentage.of.Young.Males +
                       Drug.Mortality.Rate +
                       #Law.Enforce.per.Thousand +
                       Population.logged +
                       Internet.Usage.HH +
                       Median.Vehicle.HH)
  }
  return(lm_model)
}


rape_lm_func <- function(data, y, control_V){
  data <- drop_na(data)
  if (control_V == FALSE){
    lm_model <- lm(data = data, 
                   data[[y]] ~ Concentrated.Disadvantage.Index +
                       #Percentage.of.Unemployed +
                       #Percentage.of.Female.Headed.Households +
                       #Percentage.of.Poverty +
                       #Percentage.of.MoveIn + 
                       #Percentage.of.Renter +
                       Mobility.Index +
                       Heterogeneity.Index +
                       Percentage.of.Foreign.Born + 
                       #Percentage.of.Black +
                       #Percentage.of.Hispanic + 
                       #Percentage.of.White +
                       Percentage.of.Divorced +
                       #Less.than.High.School +
                       Percentage.of.Young.Males +
                       Drug.Mortality.Rate +
                       #Law.Enforce.per.Thousand +
                       Population.logged +
                       Internet.Usage.HH)
  }
  else{
    lm_model <- lm(data = data, 
                   data[[y]] ~ Concentrated.Disadvantage.Index +
                     #Percentage.of.Unemployed +
                       #Percentage.of.Female.Headed.Households +
                       #Percentage.of.Poverty +
                       #Percentage.of.MoveIn + 
                       #Percentage.of.Renter +
                       Mobility.Index +
                       Heterogeneity.Index +
                       Percentage.of.Foreign.Born +
                       #Percentage.of.Black +
                       #Percentage.of.Hispanic + 
                       #Percentage.of.White +
                       Percentage.of.Divorced +
                       #Less.than.High.School +
                       Percentage.of.Young.Males +
                       Drug.Mortality.Rate +
                       #Law.Enforce.per.Thousand +
                       Population.logged +
                       Internet.Usage.HH +
                       Percentage.of.Indigenous)
  }
  return(lm_model)
}

```



```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
#GT_MVT 2010-2019 OLS model
m1 <- lm_func(final.data.2010_2019,
                     "GT.MVT",
                     control_Vehicle = TRUE)

#UCR_MVT 2010-2019 OLS model
m2 <- lm_func(final.data.2010_2019,
                        "UCR.MVT",
                        control_Vehicle = TRUE)

#GT_Burglary 2010-2019 OLS model
m3 <- lm_func(final.data.2010_2019,
                     "GT.Burglary",
                     control_Vehicle = FALSE)

#UCR_Burglary 2010-2019 OLS model
m4 <- lm_func(final.data.2010_2019,
                        "UCR.Burglary",
                        control_Vehicle = FALSE)

#GT_Larceny 2010-2019 OLS model
m5 <- lm_func(final.data.2010_2019,
                     "GT.Larceny",
                     control_Vehicle = FALSE)

#UCR_Larceny 2010-2019 OLS model"\\% 
m6 <- lm_func(final.data.2010_2019,
                        "UCR.Larceny",
                        control_Vehicle = FALSE)

#GT_Rape 2010-2019 OLS model
m7 <- rape_lm_func(final.data.2010_2019,
                     "GT.Rape",
                     control_V = FALSE)

#UCR_Rape 2010-2019 OLS model
m8 <- rape_lm_func(final.data.2010_2019,
                        "UCR.Rape",
                        control_V = FALSE)

#UCR_Homicide 2010-2019 OLS model
m9 <- lm_func(final.data.2010_2019,
                        "UCR.Homicide",
                        control_Vehicle = FALSE)

#UCR_Robbery 2010-2019 OLS model
m10 <- lm_func(final.data.2010_2019,
                        "UCR.Robbery",
                        control_Vehicle = FALSE)

```

```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
# Test RMSE of each model
library(Metrics)

gt_mvt_rmse <- rmse(m1$fitted.values, final.data.2010_2019$GT.MVT) #9.27
ucr_mvt_rmse <- rmse(m2$fitted.values, final.data.2010_2019$UCR.MVT) #11.38
gt_burglary_rmse <- rmse(m3$fitted.values, final.data.2010_2019$GT.Burglary) #11.82
ucr_burglary_rmse <- rmse(m4$fitted.values, final.data.2010_2019$UCR.Burglary) #9.78
gt_larceny_rmse <- rmse(m5$fitted.values, final.data.2010_2019$GT.Larceny) #6.2
ucr_larceny_rmse <- rmse(m6$fitted.values, final.data.2010_2019$UCR.Larceny) #10.80
gt_rape_rmse <- rmse(m7$fitted.values, final.data.2010_2019$GT.Rape) #7.32
ucr_rape_rmse <- rmse(m8$fitted.values, final.data.2010_2019$UCR.Rape) #12.72
ucr_homicide_rmse <- rmse(m9$fitted.values, final.data.2010_2019$UCR.Homicide) #7.092
ucr_robbery_rmse <- rmse(m10$fitted.values, final.data.2010_2019$UCR.Robbery)
total_rmse <- c(gt_mvt_rmse, ucr_mvt_rmse, gt_burglary_rmse, ucr_burglary_rmse,
                gt_larceny_rmse, ucr_larceny_rmse, gt_rape_rmse, ucr_rape_rmse, 
                ucr_homicide_rmse, ucr_robbery_rmse)


```

```{r, results = "hide", message=FALSE, warning = FALSE, echo = FALSE}
# Test Mean Absolute Error (MAE) of each model

gt_mvt_mae <- mae(m1$fitted.values, final.data.2010_2019$GT.MVT) #9.27
ucr_mvt_mae <- mae(m2$fitted.values, final.data.2010_2019$UCR.MVT) #11.38
gt_burglary_mae <- mae(m3$fitted.values, final.data.2010_2019$GT.Burglary) #11.82
ucr_burglary_mae <- mae(m4$fitted.values, final.data.2010_2019$UCR.Burglary) #9.78
gt_larceny_mae <- mae(m5$fitted.values, final.data.2010_2019$GT.Larceny) #6.2
ucr_larceny_mae <- mae(m6$fitted.values, final.data.2010_2019$UCR.Larceny) #10.80
gt_rape_mae <- mae(m7$fitted.values, final.data.2010_2019$GT.Rape) #7.32
ucr_rape_mae <- mae(m8$fitted.values, final.data.2010_2019$UCR.Rape) #12.72
ucr_homicide_mae <- mae(m9$fitted.values, final.data.2010_2019$UCR.Homicide) #7.092
ucr_robbery_mae <- mae(m10$fitted.values, final.data.2010_2019$UCR.Robbery)
total_mae <- c(gt_mvt_mae, ucr_mvt_mae, gt_burglary_mae, ucr_burglary_mae,
                gt_larceny_mae, ucr_larceny_mae, gt_rape_mae, ucr_rape_mae, 
                ucr_homicide_mae, ucr_robbery_mae)

round(total_mae, 2)

```



\newpage
\blandscape
```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}

list_of_variable_showing_names <- c(#"GT MVT", "GT Burglary", "GT Larceny", "GT Rape",
                        #"UCR MVT", "UCR Burglary", "UCR Larceny", "UCR Rape",
                        "CD Index", 
                               #"\\% Unemployed",
                               #"\\% Female Headed Households",
                               #"\\% Poverty",
                               #"\\% Move In", 
                               #"\\% Renter",
                               "Mobility Index",
                               "Heterogeneity Index",
                               "\\% Foreign Born", 
                               #"\\% Black", 
                               #"\\% Hispanic", 
                               #"\\% White", 
                               "\\% Divorced", 
                               #"\\% Less than High School", 
                               "\\% Young Males",
                               "Drug Mortality Rate",
                               #"Law Enforce per Thousand",
                               "Population(log)",
                               "\\% Internet Usage HH", 
                               "Median Vehicle HH"
                               #"\\% Native American"
                        )

stargazer(m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,
          title = "OLS Model of Google Trends and UCR Crime Estimation on Crime Factors, 2010-2019",
          omit.stat = c("rsq", "ll", "ser"),
          no.space = TRUE,
          table.placement = "h!",
          notes.append = FALSE, 
          notes = c("∗ p<0.05; ∗∗ p<0.01","GT = Google Trends Crime Estimates; MVT = Motor Vehicle Theft; HH = Household; CD = Concentrated Disadvantage"),
          notes.align = "l",
          dep.var.labels.include = F,
          column.labels = c("GT MVT", "UCR MVT", "GT Burglary", "UCR Burglary",
                            "GT Larceny", "UCR Larceny", "GT Rape", "UCR Rape",
                            "UCR Homicide", "UCR_Robbery"),
          covariate.labels = list_of_variable_showing_names,
          column.sep.width = "1.5pt",
          font.size = "small",
          digits = 2,
          add.lines = list(c("RMSE", round(total_rmse, 2)), c("MAE", round(total_mae, 2))),
          df = F,
          header=FALSE,
          star.char = c( "*", "**"),
          star.cutoffs = c(.05, .01),
          type = "html",
          out = "regression_models2.html")

```
\elandscape
\newpage




```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#write a plot function
plot_texts <- function(df, title){
  df <- drop_na(df)
  mvt_lm <- lm(data = df, UCR.MVT ~ GT.MVT)
  burglary_lm <- lm(data = df, UCR.Burglary ~ GT.Burglary)
  larceny_lm <- lm(data = df, UCR.Larceny ~ GT.Larceny)
  rape_lm <- lm(data = df, UCR.Rape ~ GT.Rape)

  #_________________________________________________
  #plot cook's distance in MVT 
  MVT_text_plot1 <- ggplot(df, aes(x = GT.MVT, 
                                   y = UCR.MVT, 
                                   label = DMA, 
                                   size = cooks.distance(mvt_lm),
                                   col = (cooks.distance(mvt_lm) > 4/(
                                     length(final.data.2010_2019$DMA) - 1 - 1))&(
                                     GT.MVT > median(df$GT.MVT)) & (
                                       UCR.MVT < median(df$UCR.MVT)
                                       ))) +
  geom_text(vjust = 2) +
  geom_point() +
  geom_abline(intercept = coef(lm(data = df, UCR.MVT~GT.MVT))[1], 
              slope = coef(lm(data = df, UCR.MVT~GT.MVT))[2],color = "gray28")+
  geom_hline(aes(yintercept=median(df$UCR.MVT), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  geom_vline(aes(xintercept=median(df$GT.MVT), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  scale_linetype_manual("Median", values = c(2,2)) +
  ylab("UCR MVT Rate (0 to 100 scale)") +
    xlab("GT MVT Estimates") +
    scale_color_manual("High\nInfluence\n&\nUnderreported\nZone",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "lightblue")) +
    guides(color = FALSE) +
    scale_size("Cook’s\nDistance") +
    xlim(0, 120) +
    ylim(-10, 110)
  #_________________________________________________
  #plot cook's distance in Burglary
  burglary_text_plot <- ggplot(df, aes(x = GT.Burglary, 
                                   y = UCR.Burglary, 
                                   label = DMA, 
                                   size = cooks.distance(burglary_lm),
                                   col = (cooks.distance(burglary_lm) > 4/(
                                     length(final.data.2010_2019$DMA) - 1 - 1))&(
                                     GT.Burglary > median(df$GT.Burglary)) & (
                                       UCR.Burglary < median(df$UCR.Burglary)
                                       ))) +
  geom_text(vjust = 2) +
  geom_point()  +
  geom_abline(intercept = coef(lm(data = df, UCR.Burglary~GT.Burglary))[1], 
              slope = coef(lm(data = df, UCR.Burglary~GT.Burglary))[2],color = "gray28")+
  geom_hline(aes(yintercept=median(df$UCR.Burglary), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  geom_vline(aes(xintercept=median(df$GT.Burglary), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  scale_linetype_manual("Median", values = c(2,2)) +
  ylab("UCR Burglary Rate (0 to 100 scale)") +
    xlab("GT Burglary Estimates") +
    scale_color_manual("High\nInfluence\n&\nUnderreported\nZone",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "lightblue")) +
    guides(color = FALSE) +
    scale_size("Cook’s\nDistance") +
    xlim(0, 120) +
    ylim(-10, 110)
  
  #_________________________________________________
  #plot cook's distance in Larceny
  larceny_text_plot <- ggplot(df, aes(x = GT.Larceny, 
                                   y = UCR.Larceny, 
                                   label = DMA, 
                                   size = cooks.distance(larceny_lm),
                                   col = (cooks.distance(larceny_lm) > 4/(
                                     length(final.data.2010_2019$DMA) - 1 - 1))&(
                                     GT.Larceny > median(df$GT.Larceny)) & (
                                       UCR.Larceny < median(df$UCR.Larceny)
                                       ))) +
  geom_text(vjust = 2) +
  geom_point() +
  geom_abline(intercept = coef(lm(data = df, UCR.Larceny~GT.Larceny))[1], 
              slope = coef(lm(data = df, UCR.Larceny~GT.Larceny))[2],color = "gray28")+
  geom_hline(aes(yintercept=median(df$UCR.Larceny), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  geom_vline(aes(xintercept=median(df$GT.Larceny), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  scale_linetype_manual("Median", values = c(2,2)) +
  ylab("UCR Larceny Rate (0 to 100 scale)") +
  xlab("GT Larceny Estimates") +
    scale_color_manual("High\nInfluence\n&\nUnderreported\nZone",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "lightblue")) +
    guides(color = FALSE) +
    scale_size("Cook’s\nDistance") +
    xlim(0, 120) +
    ylim(-10, 110)
  
  #_________________________________________________
  #plot cook's distance in Rape
  rape_text_plot <- ggplot(df, aes(x = GT.Rape, 
                                   y = UCR.Rape, 
                                   label = DMA, 
                                   size = cooks.distance(rape_lm),
                                   col = (cooks.distance(rape_lm) > 4/(
                                     length(final.data.2010_2019$DMA) - 1 - 1))&(
                                     GT.Rape > median(df$GT.Rape)) & (
                                       UCR.Rape < median(df$UCR.Rape)
                                       ))) +
  geom_text(vjust = 2) +
  geom_point() +
  geom_abline(intercept = coef(lm(data = df, UCR.Rape~GT.Rape))[1], 
              slope = coef(lm(data = df, UCR.Rape~GT.Rape))[2],color = "gray28")+
  geom_hline(aes(yintercept=median(df$UCR.Rape), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  geom_vline(aes(xintercept=median(df$GT.Rape), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  scale_linetype_manual("Median", values = c(2,2)) +
  scale_size("Cook’s\nDistance") +
  ylab("UCR Rape Rate (0 to 100 scale)") +
    xlab("GT Rape Estimates") +
    scale_color_manual("High\nInfluence\n&\nUnderreported\nZone",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "lightblue")) +
    guides(color = FALSE) +
    xlim(0, 120) +
    ylim(-10, 110)
  #_______________________________________________
  #just to get the legend
  just_to_get_the_legend1 <- ggplot(df, aes(x = GT.Rape, 
                                   y = UCR.Rape, 
                                   label = DMA, 
                                   size = cooks.distance(rape_lm),
                                   col = (cooks.distance(rape_lm) > 4/(
                                     length(final.data.2010_2019$DMA) - 1 - 1))&(
                                     GT.Rape > median(df$GT.Rape)) & (
                                       UCR.Rape < median(df$UCR.Rape)
                                       ))) +
  geom_text(vjust = 2) +
  geom_point() +
  geom_hline(aes(yintercept=median(df$UCR.Rape), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  geom_vline(aes(xintercept=median(df$GT.Rape), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  scale_linetype_manual("Median", values = c(2,2)) +
  labs(title = "Rape") + 
  scale_size("Cook’s\nDistance") +
    scale_color_manual("High Influence & In the Underreported Zone",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "lightblue")) +
    guides(size = FALSE) +
    xlim(0, 120) +
    ylim(-10, 110) +theme(legend.position = "top")
  
  #legends of Median lines
  just_to_get_the_legend2 <- ggplot(df, aes(x = GT.Rape, 
                                   y = UCR.Rape, 
                                   label = DMA
                                       )) +
  geom_hline(aes(yintercept=median(df$UCR.Rape), linetype= " "), col = "firebrick3") +
  scale_linetype_manual("Median", values = c(2,2)) + theme(legend.position = "top")
  
  #legends of Regression line
  just_to_get_the_legend3 <- ggplot(data = df, aes(x = GT.Rape, y = UCR.Rape)) +
  geom_point()+
  geom_abline(aes(intercept = coef(lm(data = df, UCR.Rape~GT.Rape))[1], 
              slope = coef(lm(data = df, UCR.Rape~GT.Rape))[2], color = ""),
              show_guide = TRUE) +
  scale_color_manual(name = "Regression Line", values=c("gray28")) + theme(legend.position = "top")
  #______________________________________________
  #blank plot
  blankPlot <- ggplot()+geom_blank(aes(1,1)) + cowplot::theme_nothing()
  
  #_______________________________________________
  #put all the cook's distance plots together
  legend_1 <- get_legend(just_to_get_the_legend1)
  legend_2 <- get_legend(just_to_get_the_legend2)
  legend_3 <- get_legend(just_to_get_the_legend3)
  final_plot <- grid.arrange( MVT_text_plot1, burglary_text_plot, larceny_text_plot, rape_text_plot, 
                               blankPlot, legend_1, legend_3, legend_2, blankPlot, ncol=6,  nrow = 3, 
                              widths = c(0.3,0.5,1,1,0.5,0.3), 
                              heights = c(2 , 2 , 0.5),
                              layout_matrix = rbind(c(1,1,1,2,2,2), c(3,3,3,4,4,4),c(5,6,6,7,8,9)),
                             top = textGrob(
                               title,hjust = 0.5, vjust = 0.5, 
                               gp=gpar(fontsize = 15,font=2))) 
  return(final_plot)
}




#"lm" dma text scatter plot
png(file="Scatter_Plot_Cook_Distance_GT_UCR.png", width = 30, height = 17, unit = "cm",
    res = 200)
plot_texts(final.data.2010_2019, "Figure 5: Scatter Plot and Cook's Distance of Google Trends and UCR Crimes in DMAs, 2010 to 2019")
dev.off()
```


```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#Only need Rape Plot
rape_lm <- lm(data = final.data.2010_2019, UCR.Rape ~ GT.Rape)
rape_text_plot <- ggplot(final.data.2010_2019, aes(x = GT.Rape, 
                                   y = UCR.Rape, 
                                   label = DMA, 
                                   size = cooks.distance(rape_lm),
                                   col = (cooks.distance(rape_lm) > 4/(
                                     length(final.data.2010_2019$DMA) - 1 - 1))&(
                                     GT.Rape > median(final.data.2010_2019$GT.Rape)) & (
                                       UCR.Rape < median(final.data.2010_2019$UCR.Rape)
                                       ))) +
  geom_text(vjust = 2) +
  geom_point() +
  geom_abline(intercept = coef(lm(data = final.data.2010_2019, UCR.Rape~GT.Rape))[1], 
              slope = coef(lm(data = final.data.2010_2019, UCR.Rape~GT.Rape))[2],color = "gray28")+
  geom_hline(aes(yintercept=median(final.data.2010_2019$UCR.Rape), linetype= " "), col = "firebrick3", show.legend = F) +
  geom_vline(aes(xintercept=median(final.data.2010_2019$GT.Rape), linetype= " "), col = "firebrick3", show.legend = F) +
  scale_linetype_manual("Median", values = c(2,2)) +
  scale_size("Cook’s\nDistance") +
  ylab(expression(italic(Rape[UCR]))) +
    xlab(expression(italic(Rape[GT]))) +
    scale_color_manual("High\nInfluence\n&\nUnderreported\nZone",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "lightblue")) +
    guides(color = FALSE) +
    xlim(20, 110) +
    ylim(20, 110)

#legends of True/False
just_to_get_the_legend1 <- ggplot(final.data.2010_2019, aes(x = GT.Rape, 
                                   y = UCR.Rape, 
                                   label = DMA, 
                                   size = cooks.distance(rape_lm),
                                   col = (cooks.distance(rape_lm) > 4/(
                                     length(final.data.2010_2019$DMA) - 1 - 1))&(
                                     GT.Rape > median(final.data.2010_2019$GT.Rape)) & (
                                       UCR.Rape < median(final.data.2010_2019$UCR.Rape)
                                       ))) +
  geom_text(vjust = 2) +
  geom_point() +
  geom_hline(aes(yintercept=median(final.data.2010_2019$UCR.Rape), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  geom_vline(aes(xintercept=median(final.data.2010_2019$GT.Rape), linetype= " "), col = "firebrick3", show.legend = FALSE) +
  scale_linetype_manual("Median", values = c(2,2)) +
  labs(title = "Rape") + 
  scale_size("Cook’s\nDistance") +
    scale_color_manual("High Influence & In the Underreported Zone",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "lightblue")) +
    guides(size = FALSE) +
    xlim(20, 110) +
    ylim(20, 110) +theme(legend.position = "top")

#legends of Median lines
just_to_get_the_legend2 <- ggplot(final.data.2010_2019, aes(x = GT.Rape, 
                                   y = UCR.Rape, 
                                   label = DMA
                                       )) +
  geom_hline(aes(yintercept=median(final.data.2010_2019$UCR.Rape), linetype= " "), col = "firebrick3") +
  scale_linetype_manual("Median", values = c(2,2)) + theme(legend.position = "top")

#legends of Regression line
just_to_get_the_legend3 <- ggplot(data = final.data.2010_2019, aes(x = GT.Rape, y = UCR.Rape)) +
  geom_point()+
  geom_abline(aes(intercept = coef(lm(data = final.data.2010_2019, UCR.Rape~GT.Rape))[1], 
              slope = coef(lm(data = final.data.2010_2019, UCR.Rape~GT.Rape))[2], color = ""),
              show_guide = TRUE) +
  scale_color_manual(name = "Regression Line", values=c("gray28")) + theme(legend.position = "top")


blankPlot <- ggplot()+geom_blank(aes(1,1)) + cowplot::theme_nothing()


#############################
legend_1 <- get_legend(just_to_get_the_legend1)
legend_2 <- get_legend(just_to_get_the_legend2)
legend_3 <- get_legend(just_to_get_the_legend3)


png(file="Scatter_Plot_Cook_Distance_GT_UCR_Rape.png", width = 15, height = 15, unit = "cm",
    res = 1080)
print(grid.arrange(rape_text_plot, legend_1, blankPlot,legend_3, legend_2, blankPlot, ncol=4,  nrow = 3, 
                              widths = c(0.2,1,1,0.2), 
                              heights = c(2 , 0.25 , 0.25),
                              layout_matrix = rbind(c(1,1,1,1), c(2,2,2,2),c(3,4,5,6))))
dev.off()


```



```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#Test the residual of GT and UCR, and test what causes the residuals
#write a function to process residual test
test_ucr_gt_residuals <- function(data, GT, UCR, year){
  data2 <- drop_na(data)
  data2_lm <- lm(data = data2, data2[[GT]] ~ data2[[UCR]])
  data2$residuals <- data2_lm$residuals 
  data2_resdiual <- lm(data = data2, residuals ~ Concentrated.Disadvantage.Index +
                       #Percentage.of.Unemployed +
                       #Percentage.of.Female.Headed.Households +
                       #Percentage.of.Poverty +
                       #Percentage.of.MoveIn + 
                       #Percentage.of.Renter +
                       Mobility.Index +
                       Heterogeneity.Index +
                       Percentage.of.Foreign.Born + 
                       #Percentage.of.Black +
                       #Percentage.of.Hispanic + 
                       #Percentage.of.White +
                       Percentage.of.Divorced +
                       #Less.than.High.School +
                       Percentage.of.Young.Males +
                       Drug.Mortality.Rate +
                       #Law.Enforce.per.Thousand +
                       Population.logged +
                       Internet.Usage.HH +
                       Median.Vehicle.HH)
  return(summary(data2_resdiual))
}
test_ucr_gt_residuals(final.data.2010_2019, "GT.MVT", "UCR.MVT", "2010_2019")

test_ucr_gt_residuals(final.data.2010_2019, "GT.Rape", "UCR.Rape", "2010_2019")

test_ucr_gt_residuals(final.data.2010_2019, "GT.Burglary", "UCR.Burglary", "2010_2019")

test_ucr_gt_residuals(final.data.2010_2019, "GT.Larceny", "UCR.Larceny", "2010_2019")


```





```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
plot_correlation <- function(df, title){
  mvtp <- round(cor.test(df$GT.MVT,df$UCR.MVT)$p.value,3)
  burglaryp <- round(cor.test(df$GT.Burglary,df$UCR.Burglary)$p.value,3)
  larcenyp <- round(cor.test(df$GT.Larceny,df$UCR.Larceny)$p.value,3)
  rapep <- round(cor.test(df$GT.Rape,df$UCR.Rape)$p.value,3)
  mvtp <- ifelse(mvtp == 0, 0.001, mvtp)
  burglaryp <- ifelse(burglaryp == 0, 0.001,burglaryp )
  larcenyp <- ifelse(larcenyp == 0, 0.001,larcenyp )
  rapep <- ifelse(rapep == 0, 0.001,rapep )
  df <- drop_na(df)
  gt_ucr <- ggplot(df) +
  geom_point(aes(x = GT.MVT, y = UCR.MVT), alpha = 0.3, size = 1, color = "brown") +
  geom_smooth(aes(x = GT.MVT, y = UCR.MVT), method = "lm") +
  geom_text(x=40, y=70, label = paste(
    "r = ", sprintf("%.3f", cor(df$GT.MVT,df$UCR.MVT,use = "complete.obs")),
    ", p-value < ", mvtp)) + 
  labs(title = "Motor Vehicle Theft") +
  theme(axis.title.y = element_blank(), axis.title.x = element_blank())
  xlim(0, 100)

  gt_ucr_burg <- ggplot(df)+
    geom_point(aes(x = GT.Burglary, y = UCR.Burglary), alpha = 0.3, size = 1) +
    geom_smooth(aes(x = GT.Burglary, y = UCR.Burglary), method = "lm")+
    geom_text(x=40, y=76, label = paste("r = ",sprintf("%.3f",cor(df$GT.Burglary,df$UCR.Burglary,use = "complete.obs")),
    ", p-value < ", burglaryp))+ 
    labs(title = "Burglary") +
    theme(axis.title.y = element_blank(), axis.title.x = element_blank())
    xlim(20, 100)
  
  gt_ucr_lar <- ggplot(df)+
    geom_point(aes(x = GT.Larceny, y = UCR.Larceny), alpha = 0.3, size = 1, color = "red")+
    geom_smooth(aes(x = GT.Larceny, y = UCR.Larceny), method = "lm")+
    geom_text(x=50, y=82, label = paste("r = ",sprintf("%.3f", cor(df$GT.Larceny,df$UCR.Larceny,use = "complete.obs")),
    ", p-value < ", larcenyp))+ 
    labs(title = "Larceny") +
    theme(axis.title.y = element_blank(), axis.title.x = element_blank())
    xlim(20, 100)
  
  gt_ucr_rape <- ggplot(df)+
    geom_point(aes(x = GT.Rape, y = UCR.Rape), alpha = 0.3, size = 1, color = "darkgreen")+
    geom_smooth(aes(x = GT.Rape, y = UCR.Rape), method = "lm") +
    geom_text(x=55, y=80, label = paste("r = ",sprintf("%.3f", cor(df$GT.Rape, df$UCR.Rape, use = "complete.obs")),
    ", p-value < ", rapep))+ 
    labs(title = "Rape") +
    theme(axis.title.y = element_blank(), axis.title.x = element_blank())
    xlim(20, 100)
  
  grid.arrange(gt_ucr, gt_ucr_burg, gt_ucr_lar, gt_ucr_rape, 
                 ncol=2, top = textGrob(
                 title, hjust = 0.5, vjust = 0.5,
                 gp=gpar(fontsize=16,font=2)),
               left = textGrob("UCR Crime Rates", rot = 90, vjust = 1, 
                               gp=gpar(fontsize = 15,fontface="bold")),
               bottom = textGrob("Google Trends Crime Estimates", 
                                 gp=gpar(fontsize = 15,fontface="bold")))
}


png(file="correlation_10_19_plot.png", width = 30, height = 17, unit = "cm",
    res = 100)
plot_correlation(final.data.2010_2019, 
                 "Figure 1, UCR, and Google Trends Correlation Scatter Plots")
dev.off()

```


```{r,  message=FALSE, warning = FALSE, echo = FALSE}

library(MASS)

#Cook's Distance Plot Function
cook_distance <- function(lm_model, text_name_column, crimetype){
  cooks_data <- data.frame(cooks.distance(lm_model), hatvalues(lm_model), studres(lm_model), text_name_column)
  colnames(cooks_data) <- cbind("cooks_dist", "hat_values", "studres", "DMA")
  
  ## Plot
  
  ggplot(cooks_data, aes(x = hat_values, y = studres,
          size = cooks_dist,
          col = cooks_dist > 4/(nrow(cooks_data) - 1 - 1),
          label = cooks_data$DMA)) +
    geom_point() + 
    geom_text(vjust = 2)  +
    geom_vline(xintercept = 2 * (lm_model$rank - 1 + 1)/nrow(cooks_data),
               linetype = 2) +
    geom_hline(yintercept = c(-4, 4), linetype = 2) +
    scale_color_manual("High\nInfluence",
                       values = c("TRUE" = "gold2",
                                  "FALSE" = "gray97")) +
    scale_size("Cook’s\nDistance") + theme_bw() +
    ggtitle(paste(crimetype)) +
    theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
    xlim(-0.28, 0.45) +
    ylim(-4.8, 4.8)
}

#Arrange Cook's Distance Plot Function
test_lm <- lm(data = final.data.2010_2019, UCR.MVT ~ GT.MVT)
test_lm$rank



arrange_cook <- function(df, title){
  df <- drop_na(df)
  ucr_gt_mvt_lm <- lm(data = df, UCR.MVT ~ GT.MVT)
  ucr_gt_mvt_cook_plot <- cook_distance(ucr_gt_mvt_lm, df$DMA, "Motor Vehicle Theft")+
    theme(legend.position="none")

  ucr_gt_larceny_lm <- lm(data = df, UCR.Larceny ~ GT.Larceny)
  ucr_gt_larceny_cook_plot <- cook_distance(ucr_gt_larceny_lm, df$DMA, "Larceny")+
    theme(legend.position="none")
  
  ucr_gt_burglary_lm <- lm(data = df, UCR.Burglary ~ GT.Burglary)
  ucr_gt_burglary_cook_plot <- cook_distance(ucr_gt_burglary_lm, df$DMA, "Burglary")+
    theme(legend.position="none")
  
  ucr_gt_rape_lm <- lm(data = df, UCR.Rape ~ GT.Rape)
  ucr_gt_rape_cook_plot <- cook_distance(ucr_gt_rape_lm, df$DMA, "Rape")+
    theme(legend.position="none")
  
  legend <- get_legend(cook_distance(ucr_gt_rape_lm, df$DMA, "Rape"))
  
  final_plot <- grid.arrange(arrangeGrob(ucr_gt_mvt_cook_plot, 
                             ucr_gt_burglary_cook_plot, 
                             ucr_gt_larceny_cook_plot, 
                             ucr_gt_rape_cook_plot, nrow = 2), 
                             legend,
                             widths=c(8, 1),
                             heights=c(200, 1),
                             ncol=2, top = textGrob(title, hjust = 0.5 , vjust = 0.5,
                                                    gp=gpar(fontsize=16,font=2)),
                             left = textGrob("Studentized Residuals", rot = 90, vjust = 1, 
                               gp=gpar(fontsize = 15,fontface="bold")),
                             bottom = textGrob("Hat Values", hjust = 0.9, 
                               gp=gpar(fontsize = 15,fontface="bold")))
  return(final_plot)
}

png(file="cook_10_19_plot.png", width = 30, height = 17, unit = "cm",
    res = 100)
arrange_cook(final.data.2010_2019, 
             "Figure 6: Influence Plot of Google Trends and UCR Crimes, 2010 to 2019")
dev.off()

```



```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#VIF Test, VIF need to be less than 4
library(caret)

xtable(cbind(car::vif(m1), 
                car::vif(m2),
                car::vif(m3),
                car::vif(m4),
                car::vif(m5),
                car::vif(m6),
                car::vif(m7),
                car::vif(m8),
                car::vif(m9),
                car::vif(m10)))

```



```{r, message=FALSE, warning = FALSE, echo = FALSE}
#Exploratory Factor Analysis
library(psych)
library(GPArotation)

efa_gt_2010_2019 <- fa(final.data.2010_2019[c(12:15,19,23,29:31)], nfactors = 3,rotate = "oblimin",fm="minres")
print(efa_gt_2010_2019$loadings,cutoff = 0.3)
print("Eigen values of the common factor solution: ")
print(efa_gt_2010_2019$values,cutoff = 0.3)

efa_gt_2010_2019 <- fa(final.data.2010_2019[c(12:15,19,23,29:31)], nfactors = 6,rotate = "oblimin",fm="minres")
print(efa_gt_2010_2019$loadings,cutoff = 0.3)
print("Eigen values of the common factor solution: ")
print(efa_gt_2010_2019$values,cutoff = 0.3)

efa_gt_2010_2019 <- fa(final.data.2010_2019[c(12:15,19,23,29:31)], nfactors = 9,rotate = "oblimin",fm="minres")
print(efa_gt_2010_2019$loadings,cutoff = 0.3)
print("Eigen values of the common factor solution: ")
print(efa_gt_2010_2019$values,cutoff = 0.3)

```

```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#Write an EFA function
efa_func <- function(crime_names, df){
  efa_gt_2010_2019 <- fa(df[[crime_names]], nfactors = 2,rotate = "oblimin",fm="minres")
  print(efa_gt_2010_2019$loadings, cutoff = 0.3)
  print("Eigen values of the common factor solution: ")
  print(efa_gt_2010_2019$values,cutoff = 0.3)
}

#EFA Table Funciton from Francisco Wilhelm 
#https://www.franciscowilhelm.com/post/exploratory-factor-analysis-table/

fa_table <- function(x, varlabels = NULL, title = "Factor analysis results", diffuse = .10, small = .50, cross = .20, sort = TRUE) {
  #get sorted loadings
  library(dplyr)
  library(purrr)
  library(tibble)
  library(gt)
  if(sort == TRUE) {
    x <- psych::fa.sort(x)
  }
  if(!is.null(varlabels)) {
    if(length(varlabels) != nrow(x$loadings)) { warning("Number of variable labels and number of variables are unequal. Check your input!",
                                                        call. = FALSE) }
    if(sort == TRUE) {
      varlabels <- varlabels[x$order]
      }
  }
  if(is.null(varlabels)) {varlabels <- rownames(x$loadings)}

  loadings <- data.frame(unclass(x$loadings))
  
  #make nice names
  factornamer <- function(nfactors) {
    paste0("Factor_", 1:nfactors)}
  
  nfactors <- ncol(loadings)
  fnames <- factornamer(nfactors)
  names(loadings) <- fnames
  
  # prepare locations
  factorindex <- apply(loadings, 1, function(x) which.max(abs(x)))
  
  # adapted from from sjplot: getremovableitems
  getRemovableItems <- function(dataframe, fctr.load.tlrn = diffuse) {
    # clear vector
    removers <- vector(length = nrow(dataframe))
    # iterate each row of the data frame. each row represents
    # one item with its factor loadings
    for (i in seq_along(removers)) {
      # get factor loadings for each item
      rowval <- as.numeric(abs(dataframe[i, ]))
      # retrieve highest loading
      maxload <- max(rowval)
      # retrieve 2. highest loading
      max2load <- sort(rowval, TRUE)[2]
      # check difference between both
      if (abs(maxload - max2load) < fctr.load.tlrn) {
        # if difference is below the tolerance,
        # remeber row-ID so we can remove that items
        # for further PCA with updated data frame
        removers[i] <- TRUE
      }
    }
    # return a vector with index numbers indicating which items
    # have unclear loadings
    return(removers)
  }
 if(nfactors > 1) {
   removable <- getRemovableItems(loadings)
   cross_loadings <- purrr::map2(fnames, seq_along(fnames), function(f, i) {
     (abs(loadings[,f] > cross)) & (factorindex != i) 
   })
 }

  small_loadings <- purrr::map(fnames, function(f) {
    abs(loadings[,f]) < small
  })
  
  ind_table <- dplyr::tibble(varlabels, loadings) %>%
    dplyr::rename(Indicator = varlabels) %>% 
    dplyr::mutate(Communality = x$communality, Uniqueness = x$uniquenesses, Complexity = x$complexity) %>% 
    dplyr::mutate(across(starts_with("Factor"), round, 3))  %>%
    dplyr::mutate(across(c(Communality, Uniqueness, Complexity), round, 2))
                    
  
  ind_table <- ind_table %>% gt(rowname_col = "Indicator") %>% tab_header(title = title)
  # mark small loadiongs
  for(f in seq_along(fnames)) {
    ind_table <- ind_table %>%  tab_style(style = cell_text(color = "#D3D3D3", style = "italic"),
                             locations = cells_body(columns = fnames[f], rows = small_loadings[[f]]))
  }
  # mark cross loadings
  
  if (nfactors > 1) {
    for (f in seq_along(fnames)) {
      ind_table <-
        ind_table %>%  tab_style(
          style = cell_text(style = "italic"),
          locations = cells_body(columns = fnames[f], rows = cross_loadings[[f]])
        )
    }
    # mark non-assignable indicators
    ind_table <-
      ind_table %>%  tab_style(style = cell_fill(color = "#D93B3B"),
                               locations = cells_body(rows = removable))
  }
  
  # adapted from https://www.anthonyschmidt.co/post/2020-09-27-efa-tables-in-r/
  Vaccounted <- x[["Vaccounted"]]
  colnames(Vaccounted) <- fnames 
  if (nfactors > 1) {
  Phi <- x[["Phi"]]
  rownames(Phi) <- fnames
  colnames(Phi) <- fnames
  f_table <- rbind(Vaccounted, Phi) %>%
    as.data.frame() %>% 
    rownames_to_column("Property") %>%
    mutate(across(where(is.numeric), round, 3)) %>%
    gt() %>% tab_header(title = "Eigenvalues, Variance Explained, and Factor Correlations for Rotated Factor Solution")
  }
  else if(nfactors == 1) {
    f_table <- rbind(Vaccounted) %>%
      as.data.frame() %>% 
      rownames_to_column("Property") %>%
      mutate(across(where(is.numeric), round, 3)) %>%
      gt() %>% tab_header(title = "Eigenvalues, Variance Explained, and Factor Correlations for Rotated Factor Solution")
  }

  return(list("ind_table" = ind_table, "f_table" = f_table))
  
}

```

```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#write an EFA function
efa_func <- function(n_factors, column_list){
  efa_gt_2010_2019 <- fa(final.data.2010_2019[column_list], nfactors = n_factors,rotate = "oblimin",fm="minres")
  print(efa_gt_2010_2019$loadings, cutoff = 0.6)
  print("Eigen values of the common factor solution: ")
  print(efa_gt_2010_2019$values,cutoff = 0.6)
  print(fa_table(efa_gt_2010_2019)$ind_table)
  print(fa.diagram(efa_gt_2010_2019))
}

run_efa_func <- function(list){
    for (i in 1:3){
      efa_func(i, list)
    }
  }
```

```{r,results ="hide", results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#test EFA maximum factors
#final.data.2010_2019[c(column_list_ucr, gt_list)]

#psych::fa.parallel(final.data.2010_2019[c(column_list_ucr, gt_list)], fm = "minres", fa = "fa")
```

```{r,results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#EFA with only UCR 
column_list_ucr <- c("UCR.MVT","UCR.Burglary","UCR.Larceny", "UCR.Rape", "UCR.Robbery", "UCR.Assault",
                     "UCR.Homicide")

#run_efa_func(column_list_ucr)

```

```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#EFA with  GT crime s

#iterate all combination from GT and then EFA with all UCR variables
#gt_list <- c("GT.MVT","GT.Burglary","GT.Larceny", "GT.Rape")

#n <- length(gt_list)
#iterate_list <- c()
#n <- length(gt_list)

#for (i in 1:n){
#  for (j in i:n){
#    iterate_list <- append(iterate_list, list(gt_list[i:j]))
#  }
#}


#for (i in iterate_list){
#  print(i)
#  column_list_one_gt_crime <- unlist(append(i, list(column_list_ucr))) 
#  run_efa_func(column_list_one_gt_crime)
#}
#we only need two factors so we limited the numbers of factors
#run_efa_func <- function(list){
#    for (i in 1:2){
#      efa_func(i, list)
#    }
#}
```


```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#EFA Test
temp_data <- final.data.2010_2019[c("GT.MVT", "UCR.MVT", "GT.Larceny", 
                                       "UCR.Homicide", "UCR.Burglary","GT.Rape",
                                        "UCR.Larceny", "UCR.Robbery",  "UCR.Rape","GT.Burglary")]
final_efa <- fa(temp_data, nfactors = 2,rotate = "oblimin",fm="minres")

efa_table <- data.frame(psych::fa.sort(final_efa$loadings[1:10,c(2,1)]))
efa_table
rownames(efa_table) <- c("GT MVT", "UCR MVT", "GT Larceny", 
                          "UCR Homicide","UCR Burglary","GT Rape",
                          "UCR Larceny","UCR Robbery", "UCR Rape", "GT Burglary")
colnames(efa_table) <- c("Factor1", "Factor2")

#sort Factor1 then Factor2
efa_table <- round(efa_table, 3)


efa_table <- efa_table %>% 
  dplyr::mutate(Factor1 = cell_spec(Factor1, 
                                  color = ifelse(Factor1 > 0.6, "black", "lightgray"))) 

efa_table <- efa_table %>% 
  dplyr::mutate(Factor2 = cell_spec(Factor2, 
                                  color = ifelse(Factor2 > 0.6, "black", "lightgray"))) 

efa_final_table <- knitr::kable(efa_table, booktabs = T, align = "lcc", format = "latex",
                                digits = 3, linesep = "",
                                caption = 'Exploratory Factor Analysis', escape = F) %>%
  kable_styling(position = "center", latex_options = c("hold_position")) %>%
  footnote(number = c("Chi Square = 30.29, p < 0.01",
                      "RMSR = 0.06; RMSEA = 0.107; TLI = 0.894","Loading cutoff = 0.6","GT = Google Tredns Crime Estimates", "MVT = Motor Vehicle Theft"),  
           footnote_as_chunk = T, threeparttable = T)%>%
  column_spec(1, width = "3cm") %>%
  column_spec(2, width = "1.75cm") %>%
  column_spec(3, width = "1.75cm")

summary(final_efa)
print(efa_final_table)
```

```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#resampling

#bootdata <- temp_data[sample(nrow(temp_data), 5000, replace=TRUE),][,c(1:2,4:5,7,10)]
#head(bootdata)

#bootdata
#temp_data <- temp_data[sample(nrow(temp_data), 1000, replace=TRUE), ]
       
#final_efa <- fa(bootdata, nfactors = 2,rotate = "oblimin",fm="minres")
#summary(final_efa)
#efa_table <- data.frame(psych::fa.sort(final_efa$loadings[1:6,]))
#efa_table

#rownames(efa_table) <- c( "GT MVT","UCR MVT","GT Larceny",
#                          "UCR Homicide","UCR Robbery","GT Rape"
#                           )
#colnames(efa_table) <- c("Factor1", "Factor2")

#sort Factor1 then Factor2
#efa_table <- round(efa_table, 3)


#efa_table <- efa_table %>% 
#  dplyr::mutate(Factor1 = cell_spec(Factor1, 
#                                  color = ifelse(Factor1 > 0.6, "black", "lightgray"))) 

#efa_table <- efa_table %>% 
#  dplyr::mutate(Factor2 = cell_spec(Factor2, 
#                                  color = ifelse(Factor2 > 0.6, "black", "lightgray"))) 
#
#efa_final_table <- knitr::kable(efa_table, booktabs = T, align = "lcc", format = "latex",
#                                digits = 3, linesep = "",
#                                caption = 'Exploratory Factor Analysis', escape = F) %>%
#  kable_styling(position = "center", latex_options = c("hold_position")) %>%
#  footnote(number = c("Chi Square = 30.29, p < 0.01",
#                      "RMSR = 0.06; RMSEA = 0.107; TLI = 0.894","Loading cutoff = 0.6","GT = Google Tredns Crime Estimates", "MVT = Motor Vehicle Theft"),  
#           footnote_as_chunk = T, threeparttable = T)%>%
#  column_spec(1, width = "3cm") %>%
#  column_spec(2, width = "1.75cm") %>%
#  column_spec(3, width = "1.75cm")


#print(efa_final_table)
```



```{r kable, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
final_efa <- fa(final.data.2010_2019[c("GT.MVT", "UCR.MVT", "GT.Larceny",
                        "UCR.Homicide",  "GT.Rape", "UCR.Burglary")], nfactors = 2,rotate = "oblimin",fm="minres")
#parallel analysis
psych::fa.parallel(final.data.2010_2019[c("GT.MVT", "UCR.MVT", "GT.Larceny",
                        "UCR.Homicide",  "GT.Rape", "UCR.Burglary")], fm = "minres", fa = "fa")
efa_table <- data.frame(psych::fa.sort(final_efa$loadings[1:6,]))


rownames(efa_table) <- c("GT MVT", "UCR MVT", "GT Larceny",
                        "UCR Burglary", "UCR Homicide", "GT Rape")
colnames(efa_table) <- c("Factor1", "Factor2")

#sort Factor1 then Factor2
efa_table <- round(efa_table[c("GT MVT", "UCR MVT", "GT Larceny",
                        "UCR Burglary", "UCR Homicide", "GT Rape"),], 3)


efa_table <- efa_table %>% 
  dplyr::mutate(Factor1 = cell_spec(Factor1, 
                                  color = ifelse(Factor1 > 0.6, "black", "lightgray"))) 

efa_table <- efa_table %>% 
  dplyr::mutate(Factor2 = cell_spec(Factor2, 
                                  color = ifelse(Factor2 > 0.6, "black", "lightgray"))) 

efa_final_table <- knitr::kable(efa_table, booktabs = T, align = "lcc", format = "latex",
                                digits = 3, linesep = "",
                                caption = 'Improved Exploratory Factor Analysis', escape = F) %>%
  kable_styling(position = "center", latex_options = c("hold_position")) %>%
  footnote(number = c("Chi Square = 3.49,  p  <  0.48",
                      "RMSA = 0.01; RMSEA = 0; TLI = 1.005","Loading cutoff = 0.6","GT = Google Tredns Crime Estimates", "MVT = Motor Vehicle Theft"),  
           footnote_as_chunk = T, threeparttable = T)%>%
  column_spec(1, width = "3cm") %>%
  column_spec(2, width = "1.75cm") %>%
  column_spec(3, width = "1.75cm")

summary(final_efa)
print(efa_final_table)
```
\newpage

```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}

#alpha test for GT and UCR crime variables
#MVT
#alpha_mvt <- cronbach(data.frame("GT MVT" = final.data.2010_2019$GT.MVT,
#                   "UCR MVT" = final.data.2010_2019$UCR.MVT))


#Burglary
#alpha_gt_burg <- cronbach(data.frame("GT Burglary" = final.data.2010_2019$GT.Burglary,
#                   "UCR MVT" = final.data.2010_2019$UCR.MVT))

#alpha_ucr_burg <-cronbach(data.frame("UCR Burglary" = final.data.2010_2019$UCR.Burglary,
#                   "UCR MVT" = final.data.2010_2019$UCR.MVT))

#alpha_ucr_gt_burg <-cronbach(data.frame("UCR Burglary" = final.data.2010_2019$UCR.Burglary,
#                   "GT Burglary" = final.data.2010_2019$GT.Burglary))

#alpha_ucr_gt_burg <-cronbach(data.frame(
#  "GT Burglary" = final.data.2010_2019$GT.Burglary,
#  "UCR Burglary" = final.data.2010_2019$UCR.Burglary,
#  "UCR MVT" = final.data.2010_2019$UCR.MVT))

#Larceny
#alpha_gt_larceny <- cronbach(data.frame("GT Larceny" = final.data.2010_2019$GT.Larceny,
#                   "UCR MVT" = final.data.2010_2019$UCR.MVT))

#alpha_ucr_larceny <- cronbach(data.frame("UCR Larceny" = final.data.2010_2019$UCR.Larceny,
#                   "UCR MVT" = final.data.2010_2019$UCR.MVT))

#alpha_ucr_gt_larceny <- cronbach(data.frame("UCR Larceny" = final.data.2010_2019$UCR.Larceny,
#                   "GT Larceny" = final.data.2010_2019$GT.MVT))

#alpha_ucr_gt_larceny <- cronbach(data.frame(
#  "GT Larceny" = final.data.2010_2019$GT.MVT,
#  "UCR Larceny" = final.data.2010_2019$UCR.Larceny,
#  "UCR MVT" = final.data.2010_2019$UCR.MVT))

#Rape
#alpha_gt_rape <- cronbach(data.frame("GT Rape" = final.data.2010_2019$GT.Rape,
#                   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))

#alpha_ucr_rape <- cronbach(data.frame("UCR Rape" = final.data.2010_2019$UCR.Rape,
#                   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))

#alpha_ucr_rape <- cronbach(data.frame("UCR Rape" = final.data.2010_2019$UCR.Rape,
#                   "GT Rape" = final.data.2010_2019$GT.Rape))



#get the detailed alpha for each item

# 
# alpha_property <- psych::alpha(data.frame(
#   "UCR MVT" = final.data.2010_2019$UCR.MVT,
#   "GT MVT" = final.data.2010_2019$GT.MVT,
#     "UCR Burglary" = final.data.2010_2019$UCR.Burglary,
#   "GT Burglary" = final.data.2010_2019$GT.Burglary,
#   "UCR Larceny" = final.data.2010_2019$UCR.Larceny,
#   "GT Larceny" = final.data.2010_2019$GT.MVT))[[2]][1]
# alpha_property$names <- rownames(alpha_property)
# 

# alpha_violent <- psych::alpha(data.frame(
#   "GT Rape" = final.data.2010_2019$GT.Rape,
#   "UCR Rape" = final.data.2010_2019$UCR.Rape,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery))[[2]][1]
# 
# alpha_violent$names <- rownames(alpha_violent)
# 
# 
# alpha_violent_improved1 <- psych::alpha(data.frame(
#   "UCR Rape" = final.data.2010_2019$UCR.Rape,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[2]][1]
# 
# alpha_violent_improved1$names <- rownames(alpha_violent_improved1)
# 
# alpha_violent_improved2 <- psych::alpha(data.frame(
#   "GT Rape" = final.data.2010_2019$GT.Rape,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[2]][1]
# 
# alpha_violent_improved2$names <- rownames(alpha_violent_improved2)
# 
# 
# alpha_violent_improved4 <- psych::alpha(data.frame(
#   "GT Rape" = final.data.2010_2019$GT.Rape,
#   "UCR Rape" = final.data.2010_2019$UCR.Rape,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery,
#   "UCR Assault" = final.data.2010_2019$UCR.Assault,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[2]][1]
# 
# alpha_violent_improved4$names <- rownames(alpha_violent_improved4)

#alpha_total <- psych::alpha(data.frame(
#  "UCR MVT" = final.data.2010_2019$UCR.MVT,
#  "GT MVT" = final.data.2010_2019$GT.MVT,
#  "UCR Burglary" = final.data.2010_2019$UCR.Burglary,
#  "GT Burglary" = final.data.2010_2019$GT.Burglary,
#  "UCR Larceny" = final.data.2010_2019$UCR.Larceny,
#  "GT Larceny" = final.data.2010_2019$GT.MVT,
#  "GT Rape" = final.data.2010_2019$GT.Rape,
#  "UCR Rape" = final.data.2010_2019$UCR.Rape,
#  "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[2]][1]
  
#alpha_total$names <- rownames(alpha_total)

#get the total alpha for all items
# library(psy)
# alpha_property_all <-  psych::alpha(data.frame(
#   "UCR MVT" = final.data.2010_2019$UCR.MVT,
#   "GT MVT" = final.data.2010_2019$GT.MVT,
#   "UCR Burglary" = final.data.2010_2019$UCR.Burglary,
#   "GT Burglary" = final.data.2010_2019$GT.Burglary,
#   "UCR Larceny" = final.data.2010_2019$UCR.Larceny,
#   "GT Larceny" = final.data.2010_2019$GT.MVT))[[1]][1]
# 
# alpha_violent_all <- psych::alpha(data.frame(
#   "GT Rape" = final.data.2010_2019$GT.Rape,
#   "UCR Rape" = final.data.2010_2019$UCR.Rape,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery))[[1]][1]

#alpha_total_all <- psych::alpha(data.frame(
#  "UCR MVT" = final.data.2010_2019$UCR.MVT,
#  "GT MVT" = final.data.2010_2019$GT.MVT,
#  "UCR Burglary" = final.data.2010_2019$UCR.Burglary,
#  "GT Burglary" = final.data.2010_2019$GT.Burglary,
#  "UCR Larceny" = final.data.2010_2019$UCR.Larceny,
#  "GT Larceny" = final.data.2010_2019$GT.MVT,
#  "GT Rape" = final.data.2010_2019$GT.Rape,
# "UCR Rape" = final.data.2010_2019$UCR.Rape,
#  "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[1]][1]
# 
# alpha_violent_improved1_all <- psych::alpha(data.frame(
#   "UCR Rape" = final.data.2010_2019$UCR.Rape,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[1]][1]
# 
# 
# alpha_violent_improved2_all <- psych::alpha(data.frame(
#   "GT Rape" = final.data.2010_2019$GT.Rape,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[1]][1]
# 
# 
# alpha_violent_improved4_all <- psych::alpha(data.frame(
#   "GT Rape" = final.data.2010_2019$GT.Rape,
#   "UCR Rape" = final.data.2010_2019$UCR.Rape,
#   "UCR Robbery" = final.data.2010_2019$UCR.Robbery,
#   "UCR Assault" = final.data.2010_2019$UCR.Assault,
#   "UCR Homicide" = final.data.2010_2019$UCR.Homicide))[[1]][1]
# 
# 
# 
# 
# 
# #put them into a table
# alpha_table <- rbind(alpha_property[order(alpha_property$raw_alpha),], 
#       alpha_violent[order(alpha_violent$raw_alpha),])
# 
# total_alpha_names <- str_replace(alpha_table$names, "\\.", " ")
# 
# alpha_table <- alpha_table %>% 
#  mutate(`alpha_all`=c(rep(alpha_property_all$raw_alpha,6),
#                                   rep(alpha_violent_all$raw_alpha,4)),
#         .before = raw_alpha)
# 
# 
# 
# alpha_table <- round(data.frame(alpha_table[,c(1,2)]), 3)
# 
# 
#   
# 
# rownames(alpha_table) <- NULL
#get the alphas
#total_alphas <- round(c(alpha_mvt$alpha, alpha_gt_burg$alpha, alpha_ucr_burg$alpha,
#  alpha_ucr_gt_burg$alpha, alpha_gt_larceny$alpha, alpha_ucr_larceny$alpha,
#  alpha_ucr_gt_larceny$alpha, alpha_gt_rape$alpha, alpha_ucr_rape$alpha, 
#  alpha_ucr_rape$alpha), 3)




#name of each tests
#total_alpha_names <- c("GT MVT & UCR MVT", "GT Burglary & UCR MVT", "UCR Burglary & UCR MVT",
#  "GT Burglary & UCR Burglary", "GT Larceny & UCR MVT", "UCR Larceny & UCR MVT",
#  "GT Larceny & UCR Larceny", "GT Rape & UCR Homicide", "UCR Rape & UCR Homicide",
#  "GT Rape & UCR Rape")



# 
# 
# alpha_table <- alpha_table %>% 
#  mutate(`total_alpha_names`= total_alpha_names,
#         .after = `alpha_all`)
# 
# 
# 
# alpha_table <- alpha_table %>% 
#  mutate(`Latent Variable`=c(rep("Property Crime Rates",6),
#                                   rep("Violent Crime Rates",4)),
#         .before = `alpha_all`)
# 
# 
# 
# final_alpha_table <- 
#   kable(alpha_table, booktabs = T, valign = 't' ,align = "lclc", 
#         format = "latex", escape = F, longtable = T, linesep = "",
#     caption = "Cronbach's Alpha Test", digits = 3, row.names = NA, 
#     col.names = linebreak(c("Latent Variables","Cronbach's Alpha",
#                             "Tested Items", "Alpha If the Item\n is Dropped"))) %>%
#   kable_styling(position = "center", latex_options = c("hold_position")) %>%
#   column_spec(1, bold = T, width = "8em") %>%
#   collapse_rows(columns = 1:2, valign = "top", latex_hline = "major") %>%
#   footnote(number = c(paste("N = ", 
#                             length(final.data.2010_2019$DMA), " DMAs."), 
#                       "GT = Google Trends Crime Estimates.", "MVT = Motor Vehicle Thefts"), 
#            footnote_as_chunk = T, threeparttable = T)
# 
# print(final_alpha_table)



```

\newpage

```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#improved violent crime alpha table
# #put them into a table
# alpha_table_improved <- rbind(alpha_violent_improved1[order(alpha_violent_improved1$raw_alpha),], 
#       alpha_violent_improved2[order(alpha_violent_improved2$raw_alpha),],
#       alpha_violent_improved4[order(alpha_violent_improved4$raw_alpha),])
# 
# alpha_table_improved <- alpha_table_improved %>% 
#  mutate(`alpha_all`=c(rep(alpha_violent_improved1_all$raw_alpha,3),
#                       rep(alpha_violent_improved2_all$raw_alpha,3), 
#                       rep(alpha_violent_improved4_all$raw_alpha,5)),
#         .before = raw_alpha)
# 
# total_alpha_improved_names <- str_replace(alpha_table_improved$names, "\\.", " ")
# alpha_table_improved <- round(data.frame(alpha_table_improved[,c(1,2)]), 3)
# 
# rownames(alpha_table_improved) <- NULL
# #get the alphas
# #total_alphas <- round(c(alpha_mvt$alpha, alpha_gt_burg$alpha, alpha_ucr_burg$alpha,
# #  alpha_ucr_gt_burg$alpha, alpha_gt_larceny$alpha, alpha_ucr_larceny$alpha,
# #  alpha_ucr_gt_larceny$alpha, alpha_gt_rape$alpha, alpha_ucr_rape$alpha, 
# #  alpha_ucr_rape$alpha), 3)
# 
# 
# 
# #name of each tests
# #total_alpha_names <- c("GT MVT & UCR MVT", "GT Burglary & UCR MVT", "UCR Burglary & UCR MVT",
# #  "GT Burglary & UCR Burglary", "GT Larceny & UCR MVT", "UCR Larceny & UCR MVT",
# #  "GT Larceny & UCR Larceny", "GT Rape & UCR Homicide", "UCR Rape & UCR Homicide",
# #  "GT Rape & UCR Rape")
# 
# 
# 
# 
# alpha_table_improved <- alpha_table_improved %>% 
#  mutate(`total_alpha_names`= total_alpha_improved_names,
#         .after = `alpha_all`)
# 
# 
# alpha_table_improved <- alpha_table_improved %>% 
#  mutate(`Latent Variable`=c(rep("Violent Crime, Model 1",3),
#                             rep("Violent Crime, Model 2",3),
#                             rep("Violent Crime, Model 3",5)),
#         .before = `alpha_all`)
# 
# 
# final_alpha_table_improved <- 
#   kable(alpha_table_improved, booktabs = T, valign = 't' ,align = "lclc", 
#         format = "latex", escape = F, longtable = T, linesep = "",
#     caption = "Cronbach's Alpha Test", digits = 3, row.names = NA, 
#     col.names = linebreak(c("Latent Variables","Cronbach's Alpha",
#                             "Tested Items", "Alpha If the Item\n is Dropped"))) %>%
#   kable_styling(position = "center", latex_options = c("hold_position")) %>%
#   column_spec(1, bold = T, width = "8em") %>%
#   collapse_rows(columns = 1:2, valign = "top", latex_hline = "major") %>%
#   footnote(number = c(paste("N = ", 
#                             length(final.data.2010_2019$DMA), " DMAs."), 
#                       "GT = Google Trends Crime Estimates.", "MVT = Motor Vehicle Thefts"), 
#            footnote_as_chunk = T, threeparttable = T)
# 
# print(final_alpha_table_improved)
```



```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#MTMM
MTMMvariables <- final.data.2010_2019[,c("GT.MVT","GT.Burglary","GT.Larceny", "GT.Rape",
                                    "UCR.MVT","UCR.Burglary","UCR.Larceny", "UCR.Rape", "UCR.Homicide")]
cor_table <- corstars(MTMMvariables)

#insert index at the end of rowname
cor_table["new"] <- c("(1)", "(2)", "(3)", "(4)",
                        "(5)", "(6)", "(7)", "(8)",
                        "(9)") 
cor_table <- cor_table[,c(9, 1:8)]


#insert index as colnames
colnames(cor_table) <- c(" ", "(1)", "(2)", "(3)", "(4)",
                        "(5)", "(6)", "(7)", "(8)")



rownames(cor_table) <- c("GT MVT", 
                         "GT Burglary", 
                         "GT Larceny", 
                         "GT Rape",
                         "UCR MVT", 
                         "UCR Burglary", 
                         "UCR Larceny", 
                         "UCR Rape",
                         "UCR Homicide")

```

\newpage
\blandscape
```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#MTMM
col_width <- "1cm"
final_corr_table <- kable(cor_table, longtable = T, booktabs = T, 
                          align = "l",
                          format = "latex", linesep = "",
    caption = 'MTMM') %>%
  kable_styling(latex_options="scale_down", font_size = 7,
                position = "float_left", bootstrap_options = "striped",
                full_width = F) %>%
  column_spec(1, bold = F, width = "3cm") %>%
  column_spec(2, bold = F, width = "0.5cm") %>%
  column_spec(3, bold = F, width = col_width) %>%
  column_spec(4, bold = F, width = col_width) %>%
  column_spec(5, bold = F, width = col_width) %>%
  column_spec(6, bold = F, width = col_width) %>%
  column_spec(7, bold = F, width = col_width) %>%
  column_spec(8, bold = F, width = col_width) %>%
  column_spec(9, bold = F, width = col_width) %>%
  footnote(number = c("** = p < .01, * = p < .05;","GT = Google Tredns Crime Estimates", "MVT = Motor Vehicle Theft"), number_title = "Note: ", 
           footnote_as_chunk = T, threeparttable = T)
print(final_corr_table, scalebox = 0.9)

```
\elandscape
\newpage

```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#CFA Test
library(lavaan)
library(foreign)

#see correlation
#cor_table

#see covariance
#mvt
round(cov(final.data.2010_2019[c(2,9)]),2)

#burglary
round(cov(final.data.2010_2019[c(3,7)]),2)

#larceny
round(cov(final.data.2010_2019[c(4,8)]),2)

#rape
round(cov(final.data.2010_2019[c(5,6)]),2)

#property crime
round(cov(final.data.2010_2019[c(2,3,4,7,8,9)]),2)

#violent crime
round(cov(final.data.2010_2019[c(5,6,10)]),2)
```

```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#Write a fucntion to produce CFA Tables
cfa_func <- function(formula, df){
  cfa_model <- cfa(formula, data=df, std.lv=TRUE) 
  print(summary(cfa_model , fit.measures=TRUE, standardized=TRUE))
  
  formated_table <- parameterEstimates(cfa_model , standardized=TRUE) %>%
    filter(op == "=~") %>%
    dplyr::select('Latent Factor'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>%
    knitr::kable(digits = 3, booktabs=TRUE, format="markdown", caption="Factor Loadings", linesep = "")
  return(formated_table)
  }
```

```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#one factor three items, variance std 
cfa_func_table <- function(formula, df){
  cfa_model_m1a <- cfa(formula, data=df, std.lv=TRUE) 
  print(summary(cfa_model_m1a , fit.measures=TRUE, standardized=TRUE))
  table_m1a <- parameterEstimates(cfa_model_m1a , standardized=TRUE)%>%
    filter(op == "=~") %>%
    dplyr::select('Latent Factor'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all)
  table_m1a <- table_m1a[c("Indicator", "Beta", "p-value")]
  return(table_m1a)
}
```


```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#Group1
m1a  <- ' f  =~  NA*UCR.MVT + UCR.Burglary + GT.MVT 
        f ~~ 1*f' 
cfa_table1 <- cfa_func_table(m1a, final.data.2010_2019)



```


```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
# Group2 
m2a <- 'f =~ NA*UCR.MVT + UCR.Burglary + GT.Larceny
        f ~~ 1*f'
cfa_table2 <- cfa_func_table(m2a, final.data.2010_2019)

```


```{r, results ="hide",message=FALSE, warning = FALSE, echo = FALSE}
 
m3a  <- ' f  =~  NA*UCR.MVT + UCR.Burglary + UCR.Larceny
        f ~~ 1*f' 
cfa_table3 <- cfa_func_table(m3a, final.data.2010_2019)
```

```{r,results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
m4a <- 'f =~ NA*UCR.MVT + UCR.Burglary + GT.Burglary
        f ~~ 1*f' 
cfa_table4 <- cfa_func_table(m4a, final.data.2010_2019)

```

```{r,results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
m5a <- 'f =~ NA*UCR.Homicide + UCR.Robbery + GT.Rape
        f ~~ 1*f' 
cfa_table5 <- cfa_func_table(m5a, final.data.2010_2019)

```

```{r, results ="hide",message=FALSE, warning = FALSE, echo = FALSE}
m6a <- 'f =~ NA*UCR.Homicide + UCR.Robbery + UCR.Rape
        f ~~ 1*f' 
cfa_table6 <- cfa_func_table(m6a, final.data.2010_2019)

```

```{r, results ="hide",message=FALSE, warning = FALSE, echo = FALSE}
#property crime CFA
property_crime_CFA_formula  <- ' f  =~  NA*UCR.MVT + UCR.Burglary + UCR.Larceny + GT.MVT + GT.Burglary + GT.Larceny 
        f ~~ 1*f' 
property_crime_CFA <- cfa_func_table(property_crime_CFA_formula, final.data.2010_2019)
```

```{r, results ="hide",message=FALSE, warning = FALSE, echo = FALSE}
#property crime CFA drop GT.Burglary and UCR.Larceny
property_crime_CFA_formula_2  <- 'f  =~  NA*UCR.MVT + UCR.Burglary + GT.MVT
        f ~~ 1*f' 
property_crime_CFA_2 <- cfa_func_table(property_crime_CFA_formula_2, final.data.2010_2019)
```


```{r, results ="hide",message=FALSE, warning = FALSE, echo = FALSE}
#violent crime CFA
violent_crime_CFA_formula  <- 'f =~ NA*UCR.Homicide + UCR.Robbery + UCR.Rape + GT.Rape 
        f ~~ 1*f' 
violent_crime_CFA <- cfa_func_table(violent_crime_CFA_formula, final.data.2010_2019)
```

```{r, results ="hide",message=FALSE, warning = FALSE, echo = FALSE}
#violent crime CFA
violent_crime_CFA_formula_2  <- 'f =~ NA*UCR.Homicide + UCR.Robbery +  GT.Rape + UCR.Burglary
        f ~~ 1*f' 
violent_crime_CFA_2 <- cfa_func_table(violent_crime_CFA_formula_2, final.data.2010_2019)
```




```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#combine all CFA tables

cfa_table <- rbind(cfa_table1, cfa_table2, cfa_table3, cfa_table4,
                   cfa_table5, cfa_table6)
cfa_table <- cfa_table %>% mutate(RMSEA = c(0, "","", 0, "","", 0, "","", 
                                            0, "","", 0, "","", 0, "",""))
cfa_table <- cfa_table %>% mutate(TLI = c(1, "", "", 1, "","", 1, "","", 
                                          1, "", "", 1, "","", 1, "",""))
cfa_table <- cfa_table %>% mutate(TLI = c(1, "", "", 1, "","", 1, "","", 
                                          1, "", "", 1, "","", 1, "",""))
cfa_table$Indicator <- c("UCR MVT", "UCR Burglary", "GT MVT", 
                         "UCR MVT", "UCR Burglary", "GT Larceny", 
                         "UCR MVT", "UCR Burglary", "UCR Larceny",
                         "UCR MVT", "UCR Burglary", "GT Burglary",
                         "UCR Homicide", "UCR Robbery","GT Rape", 
                         "UCR Homicide", "UCR Robbery","UCR Rape")

colnames(cfa_table)[colnames(cfa_table) == 'Beta'] <- 'Standardized Loadings'

cfa_final_table <- knitr::kable(cfa_table, booktabs = T, align = "lccc", format = "latex",
                                digits = 3, linesep = "",
                                caption = 'Confirmatory Factor Analysis', escape = F) %>%
  kable_styling(position = "center", latex_options = c("hold_position")) %>%
  footnote(number = c("GT = Google Tredns Crime Estimates", "MVT = Motor Vehicle Theft"),  
           footnote_as_chunk = T, threeparttable = T)%>%
  pack_rows("Property Crime Model 1", 1, 3) %>%
  pack_rows("Property Crime Model 2", 4, 6) %>%
  pack_rows("Property Crime Model 3", 7, 9) %>%
  pack_rows("Property Crime Model 4", 10, 12) %>%
  pack_rows("Violent Crime Model 1", 13, 15) %>%
  pack_rows("Violent Crime Model 2", 16, 18) %>%
  column_spec(1, width = "3cm") %>%
  column_spec(2, width = "1.5cm") %>%
  column_spec(3, width = "1.5cm") %>%
  column_spec(4, width = "1.5cm") %>%
  column_spec(5, width = "1.5cm")


print(cfa_final_table)
```


```{r, results ="hide", message=FALSE, warning = FALSE, echo = FALSE}
#obtain implied variance covariance matrix
#inspect(onefac3items_a,"cov.ov")
```



```{r, results ="hide",  message=FALSE, warning = FALSE, echo = FALSE}

res <- cor(final.data.2010_2019[3:10,12:31])

write.csv(round(res, 3),file="GT_ACS_cormatrix.csv")

```


```{r,  message=FALSE, warning = FALSE, echo = FALSE}
library(ggplot2)
library(gridExtra)

h1 <- ggplot(final.data.2010_2019, aes(x=GT.MVT)) + 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Motor Vehicle Theft") +
  xlim(0,100)

h2 <- ggplot(final.data.2010_2019, aes(x=GT.Burglary))+ 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Burglary") +
  xlim(0,100)

h3 <- ggplot(final.data.2010_2019, aes(x=GT.Larceny)) + 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Larceny") +
  xlim(0,100)

h4 <- ggplot(final.data.2010_2019, aes(x=GT.Rape)) + 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Rape") +
  xlim(0,100)

gt_hist_title <- "Figure 2, Histogram of Google Trends Crime Estimates"

png(file="hist_GT_2010_2019.png", width = 30, height = 17, unit = "cm",
    res = 200)
grid.arrange(h1, h2, h3, h4, 
          ncol = 2, nrow = 2, 
          top = textGrob(gt_hist_title, hjust = 0.5 , vjust = 0.5, 
                         gp=gpar(fontsize=15,font=2)),
          left = textGrob("Counts", rot = 90, vjust = 1, gp=gpar(fontsize = 15,fontface="bold")),
          bottom = textGrob("Google Trends Crime Estimates Distributions", 
                            gp=gpar(fontsize = 15,fontface="bold")))

dev.off()


```


```{r,  message=FALSE, warning = FALSE, echo = FALSE}
h5 <- ggplot(final.data.2010_2019, aes(x=UCR.MVT)) + 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Motor Vehicle Theft") +
  xlim(0,100)

h6 <- ggplot(final.data.2010_2019, aes(x=UCR.Burglary)) + 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Burglary") +
  xlim(0,100)

h7 <- ggplot(final.data.2010_2019, aes(x=UCR.Larceny)) + 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Larceny") +
  xlim(0,100)

h8 <- ggplot(final.data.2010_2019, aes(x=UCR.Rape))  + 
  geom_histogram() + 
  theme(axis.title.y = element_blank(), axis.title.x = element_blank()) +
  labs(title = "Rape") +
  xlim(0,100)

ucr_hist_title <- "Figure 3, Histogram of Uniform Crime Report Crime Rates"

png(file="hist_UCR_2010_2019.png", width = 30, height = 17, unit = "cm",
    res = 200)
grid.arrange(h5, h6, h7, h8, ncol = 2, 
          top = textGrob(ucr_hist_title, hjust = 0.5, vjust = 0.5, 
                         gp=gpar(fontsize = 15,font=2)),
          left = textGrob("Counts", rot = 90, vjust = 1, gp=gpar(fontsize = 15,fontface="bold")),
          bottom = textGrob("Uniform Crime Report Crime Rates Distributions", 
                            gp=gpar(fontsize = 15,fontface="bold")))
dev.off()


```

```{r,  message=FALSE, warning = FALSE, echo = FALSE}
gt_rape_ucr_himicide <- ggplot(final.data.2010_2019)+
    geom_point(aes(x = GT.Rape, y = UCR.Homicide), alpha = 0.3, size = 1, color = "darkgreen")+
    geom_smooth(aes(x = GT.Rape, y = UCR.Homicide), method = "lm") +
    labs(title = "Rape") +
    theme(axis.title.y = element_blank(), axis.title.x = element_blank())
    xlim(20, 100)
gt_rape_ucr_himicide

ucr_rape_ucr_himicide <- ggplot(final.data.2010_2019)+
    geom_point(aes(x = UCR.Rape, y = UCR.Homicide), alpha = 0.3, size = 1, color = "darkgreen")+
    geom_smooth(aes(x = UCR.Rape, y = UCR.Homicide), method = "lm") +
    labs(title = "Rape") +
    theme(axis.title.y = element_blank(), axis.title.x = element_blank())
    xlim(20, 100)

```

\newpage
```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
#Significance and Directions
rownames <- list_of_variable_showing_names[1:7]
GT_MVT <-       c("+", "+", "+", " ", " ", " ", " ")
UCR_MVT <-      c("+", "+", "+", " ", " ", "-", " ")
GT_Burglary <-  c("+", " ", " ", " ", " ", " ", " ")
UCR_Burglary <- c("+", " ", "+", "-", "+", " ", " ")
GT_Larceny <-   c("+", " ", " ", "+", "+", "+", " ")
UCR_Larceny <-  c("+", " ", " ", "-", " ", " ", " ")
GT_Rape <-      c("+", " ", " ", "-", " ", " ", " ")
UCR_Rape <-     c(" ", " ", " ", " ", "+", "+", " ")
UCR_Homicide <- c("+", " ", "+", "-", " ", " ", " ")

col_wid <- "2cm"
simple_regression_t <- cbind(GT_MVT, UCR_MVT, GT_Burglary,
                             UCR_Burglary, GT_Larceny, UCR_Larceny,
                             GT_Rape, UCR_Rape, UCR_Homicide)

rownames(simple_regression_t) <- c("CD Index","Mobility Index",
                                   "Heterogeneity Index",
                                   "\\% Foreign Born",
                                   "\\% Divorced",
                                   "\\% Young Males",
                                   "Drug Mortality Rate")
colnames(simple_regression_t) <- c("GT MVT", "UCR MVT", "GT Burglary", "UCR Burglary",
                             "GT Larceny", "UCR Larceny", "GT Rape", "UCR Rape",
                             "UCR Homicide")


simple_regression_final_t <- kbl(simple_regression_t, booktabs = T, align = "ccccccccc", format = "latex",
                                 linesep = "", escape = F,
    caption = "Summary of Multiple Regression Results") %>%
  kable_styling(position = "center", 
                latex_options = c("hold_position",
                                  "striped",
                                  "scale_down")) %>%
  footnote(number = c("+ = positive association","- = negative association","GT = Google Trends Crime Estimates.", "CD = concentrated disadvantage"), footnote_as_chunk = T, threeparttable = T) 
print(simple_regression_final_t)
```



```{r,  message=FALSE, warning = FALSE, echo = FALSE}
#write.csv(final.data.2010_2019,file="final_data_2010_2019.csv")
```

\newpage

```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}


acronyms <- tribble(
    ~Abbreviation, ~ Explanation,
    "GT", "Google Trends",
    "UCR", "Federal Bureau of Investigation's Uniform Crime Report ",
    "MVT", "Motor Vehicle Theft",
    "NCVS", "National Crime Victimization Survey",
    "ARIMA", "autoregressive integrated moving average",
    "EFA", "exploratory factor analysis",
    "CFA", "confirmatory factor analysis",
    "DMA", "designated market area",
    "MLR", "multiple linear regression",
    "MAE", "mean absolute error",
    "RMSE", "root mean square error",
    "ACS", "American Community Survey",
    "CD", "concentrated disadvantage",
    "NCHS", "National Center for Health Statistics",
    "VIFs","variance inflation factors"
) %>%
    arrange(Abbreviation)

kable(data.frame(acronyms), "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  cat(., file = "acronyms.html")
```

\newpage

```{r,  message=FALSE, warning = FALSE, echo = FALSE}
t1<-read.csv("murder2010_2019.csv")
t2 <- merge(t1, final.data.2010_2019[c("DMA", "UCR.Homicide")], by = "DMA")
#cor(t2$GT.Murder, t2$UCR.Homicide)
```

```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
DMA_chart_table <- kable(DMA_chart, format = "latex", align = "rrrr", longtable = TRUE)%>%
  kable_styling(position = "center", font_size = 6.0,
                latex_options = c("hold_position",
                                  "striped",
                                  "scale_down")) 

print(DMA_chart_table, row.names=F)
```


```{r, results = "asis", message=FALSE, warning = FALSE, echo = FALSE}
kable(DMA_chart, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  cat(., file = "DMA_chart_table.html")
```

